"""Workflow definitions and YAML rendering."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from continuous.config import Config, WorkflowConfig

# Marker comments for project setup sections
SETUP_START = "# --- project setup (edit this section) ---"
SETUP_END = "# --- end project setup ---"

# Header comment on all generated files
HEADER = "# Generated by continuous — do not edit outside the project setup section.\n# Regenerate with: uvx continuous update\n"


def _bot_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.bot_token_secret} }}}}"


def _claude_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.claude_token_secret} }}}}"


def _append_sys_prompt(lines: list[str], cfg: Config) -> None:
    """Add system_prompt_append to the action block if configured."""
    if cfg.system_prompt_append:
        lines.append(f'          system_prompt_append: "{cfg.system_prompt_append}"')


def _permissions(*, issues: bool = True) -> dict:
    perms = {
        "contents": "write",
        "pull-requests": "write",
        "id-token": "write",
        "actions": "read",
    }
    if issues:
        perms["issues"] = "write"
    return perms


@dataclass
class GeneratedWorkflow:
    filename: str
    content: str


def generate_review(cfg: Config) -> GeneratedWorkflow:
    pr_num = "${{ github.event.pull_request.number }}"
    return GeneratedWorkflow(
        filename="cd-review.yaml",
        content=_render_review_yaml(cfg, pr_num),
    )


def _escape_yaml_expr(s: str) -> str:
    """Escape single quotes for use inside GitHub Actions expressions."""
    return s.replace("'", "''")


def _render_review_yaml(cfg: Config, pr_num: str) -> str:
    """Render the review workflow with inline steps."""
    lines = [HEADER]
    lines.append("name: cd-review")
    lines.append("on:")
    lines.append("  pull_request_target:")
    lines.append("    types: [opened, synchronize, ready_for_review, reopened]")
    lines.append("  pull_request_review:")
    lines.append("    types: [submitted]")
    lines.append("")
    lines.append("jobs:")
    lines.append("  review:")
    lines.append("    if: |")
    lines.append(f"      (github.event_name == 'pull_request_target' &&")
    lines.append(f"        github.event.pull_request.draft == false) ||")
    lines.append(f"      (github.event_name == 'pull_request_review' &&")
    lines.append(f"        github.event.pull_request.user.login == '{cfg.bot_name}' &&")
    lines.append(f"        github.event.review.user.login != '{cfg.bot_name}' &&")
    lines.append(f"        (github.event.review.state != 'approved' || github.event.review.body))")
    lines.append("    concurrency:")
    lines.append("      group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number }}")
    lines.append("      cancel-in-progress: true")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    timeout-minutes: 60")
    lines.append("    permissions:")
    for k, v in _permissions().items():
        lines.append(f"      {k}: {v}")
    lines.append("    steps:")

    # Checkout — merge ref for initial review, default for review response
    lines.append("      - name: Checkout (initial review)")
    lines.append("        if: github.event_name == 'pull_request_target'")
    lines.append("        uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append(f"          ref: refs/pull/{pr_num}/merge")
    lines.append("          fetch-depth: 0")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")
    lines.append("      - name: Checkout (review response)")
    lines.append("        if: github.event_name == 'pull_request_review'")
    lines.append("        uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append("          fetch-depth: 0")
    lines.append("          fetch-tags: true")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")

    # Project setup
    lines.append(f"      {SETUP_START}")
    lines.append(f"      {SETUP_END}")
    lines.append("")

    # Check out PR branch for review response
    lines.append("      - name: Check out PR branch (review response)")
    lines.append("        if: github.event_name == 'pull_request_review'")
    lines.append(f"        run: gh pr checkout {pr_num}")
    lines.append("        env:")
    lines.append(f"          GH_TOKEN: {_bot_token(cfg)}")
    lines.append("")

    # Continuous action — use format() to avoid nested ${{ }} expressions
    wf = cfg.workflows.get("review", WorkflowConfig())
    raw_prompt = wf.prompt or "/cd-review {pr_number}"
    # Replace placeholder with format() positional arg
    review_fmt = _escape_yaml_expr(raw_prompt.replace("{pr_number}", "{0}"))
    needs_format = "{0}" in review_fmt

    lines.append("      - uses: max-sixty/continuous@v1")
    lines.append("        with:")
    lines.append(f"          github_token: {_bot_token(cfg)}")
    lines.append(f"          claude_code_oauth_token: {_claude_token(cfg)}")
    lines.append(f"          bot_name: {cfg.bot_name}")
    lines.append(f'          bot_id: "{cfg.bot_id}"')
    _append_sys_prompt(lines, cfg)
    lines.append(f"          trigger_phrase: \"@{cfg.bot_name}\"")
    lines.append("          use_sticky_comment: ${{ github.event_name == 'pull_request_target' }}")
    lines.append(f"          prompt: >-")
    lines.append(f"            ${{{{ github.event_name == 'pull_request_target'")
    if needs_format:
        lines.append(f"              && format('{review_fmt}', github.event.pull_request.number)")
    else:
        lines.append(f"              && '{review_fmt}'")
    lines.append(f"              || format(")
    lines.append(f"                'A review was submitted on your PR #{{0}} ({{1}}). Read the review and full PR context (description, diff, comments, CI status), then respond appropriately. If changes were requested, make them, commit, and push. If questions were asked, answer them.',")
    lines.append(f"                github.event.pull_request.number,")
    lines.append(f"                github.event.review.html_url")
    lines.append(f"              ) }}}}")

    lines.append("")
    return "\n".join(lines) + "\n"


def generate_mention(cfg: Config) -> GeneratedWorkflow:
    """Generate the mention workflow — the most complex one."""
    lines = [HEADER]
    lines.append("name: cd-mention")
    lines.append("on:")
    lines.append("  issues:")
    lines.append("    types: [edited]")
    lines.append("  issue_comment:")
    lines.append("    types: [created, edited]")
    lines.append("  pull_request_review_comment:")
    lines.append("    types: [created, edited]")
    lines.append("")
    lines.append("jobs:")

    # Verify job — engagement verification
    lines.append("  verify:")
    lines.append("    if: |")
    lines.append(f"      (github.event_name == 'issues' &&")
    lines.append(f"        contains(github.event.issue.body, '@{cfg.bot_name}') &&")
    lines.append(f"        github.event.issue.user.login != '{cfg.bot_name}') ||")
    lines.append(f"      (github.event_name == 'issue_comment' &&")
    lines.append(f"        github.event.comment.user.login != '{cfg.bot_name}') ||")
    lines.append(f"      (github.event_name == 'pull_request_review_comment' &&")
    lines.append(f"        github.event.comment.user.login != '{cfg.bot_name}')")
    lines.append("    concurrency:")
    lines.append("      group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}")
    lines.append("      cancel-in-progress: true")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    outputs:")
    lines.append("      should_run: ${{ steps.check.outputs.should_run }}")
    lines.append("    steps:")
    lines.append("      - name: Verify bot engagement")
    lines.append("        id: check")
    lines.append("        run: |")
    # Engagement verification script — parameterized with bot_name
    lines.append("          # Mentions always run")
    lines.append('          if [ "$EVENT_NAME" = "issues" ]; then')
    lines.append('            echo "should_run=true" >> "$GITHUB_OUTPUT"')
    lines.append("            exit 0")
    lines.append("          fi")
    lines.append("")
    lines.append(f"          if [ -n \"$COMMENT_BODY\" ] && printf '%s\\n' \"$COMMENT_BODY\" | grep -qF '@{cfg.bot_name}'; then")
    lines.append('            echo "should_run=true" >> "$GITHUB_OUTPUT"')
    lines.append("            exit 0")
    lines.append("          fi")
    lines.append("")
    lines.append("          # Non-mention: check bot engagement")
    lines.append('          if [ "$EVENT_NAME" = "issue_comment" ]; then')
    lines.append('            ISSUE_NUMBER="${{ github.event.issue.number }}"')
    lines.append("")
    lines.append('            if [ -z "${{ github.event.issue.pull_request.url }}" ]; then')
    lines.append('              ISSUE_AUTHOR="${{ github.event.issue.user.login }}"')
    lines.append(f'              if [ "$ISSUE_AUTHOR" = "{cfg.bot_name}" ]; then')
    lines.append('                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("              fi")
    lines.append(f"              if echo \"$ISSUE_BODY\" | grep -qF '@{cfg.bot_name}'; then")
    lines.append('                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("              fi")
    lines.append('              BOT_COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \\')
    lines.append(f"                --jq '[.[] | select(.user.login == \"{cfg.bot_name}\")] | length')")
    lines.append('              if [ "$BOT_COMMENTS" -gt "0" ]; then')
    lines.append('                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("              fi")
    lines.append('              echo "should_run=false" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("            fi")
    lines.append("")
    lines.append('            PR_NUMBER="$ISSUE_NUMBER"')
    lines.append("          else")
    lines.append('            PR_NUMBER="${{ github.event.pull_request.number }}"')
    lines.append("          fi")
    lines.append("")
    lines.append('          PR_AUTHOR=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json author --jq \'.author.login\')')
    lines.append(f'          if [ "$PR_AUTHOR" = "{cfg.bot_name}" ]; then')
    lines.append('            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("          fi")
    lines.append("")
    lines.append('          BOT_REVIEWS=$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \\')
    lines.append(f"            --jq '[.[] | select(.user.login == \"{cfg.bot_name}\")] | length')")
    lines.append('          if [ "$BOT_REVIEWS" -gt "0" ]; then')
    lines.append('            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("          fi")
    lines.append("")
    lines.append('          BOT_COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \\')
    lines.append(f"            --jq '[.[] | select(.user.login == \"{cfg.bot_name}\")] | length')")
    lines.append('          if [ "$BOT_COMMENTS" -gt "0" ]; then')
    lines.append('            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0')
    lines.append("          fi")
    lines.append("")
    lines.append('          echo "should_run=false" >> "$GITHUB_OUTPUT"')
    lines.append("        env:")
    lines.append(f"          GH_TOKEN: {_bot_token(cfg)}")
    lines.append("          EVENT_NAME: ${{ github.event_name }}")
    lines.append("          COMMENT_BODY: ${{ github.event.comment.body }}")
    lines.append("          ISSUE_BODY: ${{ github.event.issue.body }}")
    lines.append("")

    # React to mention
    lines.append("      - name: React to mention")
    lines.append("        if: |")
    lines.append("          steps.check.outputs.should_run == 'true'")
    lines.append("          && github.event.comment")
    lines.append(f"          && contains(github.event.comment.body, '@{cfg.bot_name}')")
    lines.append("        run: |")
    lines.append('          gh api "repos/$REPO/issues/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || \\')
    lines.append('          gh api "repos/$REPO/pulls/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || true')
    lines.append("        env:")
    lines.append("          REPO: ${{ github.repository }}")
    lines.append("          COMMENT_ID: ${{ github.event.comment.id }}")
    lines.append(f"          GH_TOKEN: {_bot_token(cfg)}")
    lines.append("")

    # Handler job — single job that handles all three event types
    lines.append("  handle:")
    lines.append("    needs: verify")
    lines.append("    if: needs.verify.outputs.should_run == 'true'")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    timeout-minutes: 60")
    lines.append("    permissions:")
    for k, v in _permissions().items():
        lines.append(f"      {k}: {v}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append("          fetch-depth: 0")
    lines.append("          fetch-tags: true")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")

    # Project setup
    lines.append(f"      {SETUP_START}")
    lines.append(f"      {SETUP_END}")
    lines.append("")

    # Check out PR branch if applicable
    lines.append("      - name: Check out PR branch")
    lines.append("        if: |")
    lines.append("          (github.event_name == 'issue_comment' && github.event.issue.pull_request.url != '') ||")
    lines.append("          github.event_name == 'pull_request_review_comment'")
    lines.append("        run: |")
    lines.append("          PR_NUMBER=${{ github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number }}")
    lines.append('          PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq \'.state\')')
    lines.append('          if [ "$PR_STATE" = "OPEN" ]; then')
    lines.append('            gh pr checkout "$PR_NUMBER"')
    lines.append("          else")
    lines.append('            echo "::warning::PR is $PR_STATE — staying on default branch"')
    lines.append("          fi")
    lines.append("        env:")
    lines.append(f"          GH_TOKEN: {_bot_token(cfg)}")
    lines.append("")

    # Build prompt expressions for each event type.
    # These are used inside ${{ }}, so no ${{ }} wrapping.
    pr_number_expr = "(github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number)"
    is_mention_comment = f"contains(github.event.comment.body, '@{cfg.bot_name}')"
    is_issue_edit = "github.event_name == 'issues'"
    is_review_comment = "github.event_name == 'pull_request_review_comment'"

    lines.append("      - uses: max-sixty/continuous@v1")
    lines.append("        with:")
    lines.append(f"          github_token: {_bot_token(cfg)}")
    lines.append(f"          claude_code_oauth_token: {_claude_token(cfg)}")
    lines.append(f"          bot_name: {cfg.bot_name}")
    lines.append(f'          bot_id: "{cfg.bot_id}"')
    _append_sys_prompt(lines, cfg)
    lines.append("          prompt: >-")

    # Issue edit prompt
    lines.append(f"            ${{{{ {is_issue_edit}")
    lines.append(f"              && format('An issue was updated with a mention of you ({{0}}). Read it and respond.', github.event.issue.html_url)")

    # Review comment prompts (mention vs engaged)
    lines.append(f"              || ({is_review_comment} && {is_mention_comment}")
    lines.append(f"                && format('You were mentioned in an inline review comment on PR #{{0}} ({{1}}, review comment ID {{2}}). Read the full PR context (description, diff, recent comments, CI status) and respond. If they are requesting changes, make the changes, commit, and push. Reply in the review thread using `gh api repos/{{3}}/pulls/{{0}}/comments/{{2}}/replies -f body=\"...\"` — do not create a new top-level comment.', {pr_number_expr}, github.event.comment.html_url, github.event.comment.id, github.repository))")
    lines.append(f"              || ({is_review_comment}")
    lines.append(f"                && format('A user left an inline review comment on a PR where you previously participated (PR #{{0}}, {{1}}, review comment ID {{2}}). Read the full context. Only respond if the comment is directed at you or requests changes. Reply in the review thread using `gh api repos/{{3}}/pulls/{{0}}/comments/{{2}}/replies -f body=\"...\"`.', {pr_number_expr}, github.event.comment.html_url, github.event.comment.id, github.repository))")

    # Issue comment prompts (mention vs engaged)
    lines.append(f"              || ({is_mention_comment}")
    lines.append(f"                && format('You were mentioned in a comment ({{0}}). Read the full issue or PR (description, diff, recent comments, CI status) and respond. If they are requesting changes, make the changes, commit, and push.', github.event.comment.html_url))")
    lines.append(f"              || format('A user commented on an issue/PR where you previously participated ({{0}}). Read the full context. Only respond if the comment is directed at you, asks a question you can help with, or requests changes you can make. If the conversation is between humans, exit silently.', github.event.comment.html_url)")
    lines.append("            }}")

    lines.append("")
    return GeneratedWorkflow(
        filename="cd-mention.yaml",
        content="\n".join(lines) + "\n",
    )


def generate_triage(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("triage", WorkflowConfig())
    prompt = wf.prompt or "/cd-triage {issue_number}"
    prompt = prompt.replace("{issue_number}", "${{ github.event.issue.number }}")

    lines = [HEADER]
    lines.append("name: cd-triage")
    lines.append("on:")
    lines.append("  issues:")
    lines.append("    types: [opened]")
    lines.append("")
    lines.append("concurrency:")
    lines.append("  group: ${{ github.workflow }}-${{ github.event.issue.number }}")
    lines.append("  cancel-in-progress: true")
    lines.append("")
    lines.append("jobs:")
    lines.append("  triage:")
    lines.append("    if: >-")
    lines.append("      github.event.issue.user.type != 'Bot' &&")
    lines.append(f"      github.event.issue.user.login != '{cfg.bot_name}'")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    timeout-minutes: 60")
    lines.append("    permissions:")
    for k, v in _permissions().items():
        lines.append(f"      {k}: {v}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append("          ref: main")
    lines.append("          fetch-depth: 0")
    lines.append("          fetch-tags: true")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")
    lines.append(f"      {SETUP_START}")
    lines.append(f"      {SETUP_END}")
    lines.append("")
    lines.append("      - uses: max-sixty/continuous@v1")
    lines.append("        with:")
    lines.append(f"          github_token: {_bot_token(cfg)}")
    lines.append(f"          claude_code_oauth_token: {_claude_token(cfg)}")
    lines.append(f"          bot_name: {cfg.bot_name}")
    lines.append(f'          bot_id: "{cfg.bot_id}"')
    _append_sys_prompt(lines, cfg)
    lines.append(f"          prompt: \"{prompt}\"")

    lines.append("")
    return GeneratedWorkflow(
        filename="cd-triage.yaml",
        content="\n".join(lines) + "\n",
    )


def generate_ci_fix(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("ci-fix", WorkflowConfig())
    watched = wf.watched_workflows or ["ci"]
    prompt = wf.prompt or "/fix-ci {run_id}"

    prompt_expr = prompt.replace("{run_id}", "${{ github.event.workflow_run.id }}")

    lines = [HEADER]
    lines.append("name: cd-ci-fix")
    lines.append("on:")
    lines.append("  workflow_run:")
    lines.append(f"    workflows: [{', '.join(watched)}]")
    lines.append("    types: [completed]")
    lines.append("    branches: [main]")
    lines.append("")
    lines.append("jobs:")
    lines.append("  fix-ci:")
    lines.append("    if: github.event.workflow_run.conclusion == 'failure'")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    timeout-minutes: 60")
    lines.append("    permissions:")
    for k, v in _permissions(issues=False).items():
        lines.append(f"      {k}: {v}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append("          ref: main")
    lines.append("          fetch-depth: 0")
    lines.append("          fetch-tags: true")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")
    lines.append(f"      {SETUP_START}")
    lines.append(f"      {SETUP_END}")
    lines.append("")
    lines.append("      - uses: max-sixty/continuous@v1")
    lines.append("        with:")
    lines.append(f"          github_token: {_bot_token(cfg)}")
    lines.append(f"          claude_code_oauth_token: {_claude_token(cfg)}")
    lines.append(f"          bot_name: {cfg.bot_name}")
    lines.append(f'          bot_id: "{cfg.bot_id}"')
    _append_sys_prompt(lines, cfg)
    lines.append("          prompt: |")
    lines.append(f"            {prompt_expr}")
    lines.append("            - Run URL: ${{ github.event.workflow_run.html_url }}")
    lines.append("            - Commit: ${{ github.event.workflow_run.head_sha }}")
    lines.append("            - Commit message: ${{ github.event.workflow_run.head_commit.message }}")

    lines.append("")
    return GeneratedWorkflow(
        filename="cd-ci-fix.yaml",
        content="\n".join(lines) + "\n",
    )


def _generate_scheduled(cfg: Config, name: str, default_cron: str, default_prompt: str) -> GeneratedWorkflow:
    """Generate a simple scheduled workflow (nightly, renovate)."""
    wf = cfg.workflows.get(name, WorkflowConfig())
    cron = wf.cron or default_cron
    prompt = wf.prompt or default_prompt

    lines = [HEADER]
    lines.append(f"name: cd-{name}")
    lines.append("on:")
    lines.append("  schedule:")
    lines.append(f"    - cron: '{cron}'")
    lines.append("  workflow_dispatch:")
    lines.append("")
    lines.append("jobs:")
    lines.append(f"  {name}:")
    lines.append("    runs-on: ubuntu-24.04")
    lines.append("    timeout-minutes: 60")
    lines.append("    permissions:")
    for k, v in _permissions().items():
        lines.append(f"      {k}: {v}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v6")
    lines.append("        with:")
    lines.append("          ref: main")
    lines.append("          fetch-depth: 0")
    lines.append("          fetch-tags: true")
    lines.append(f"          token: {_bot_token(cfg)}")
    lines.append("")
    lines.append(f"      {SETUP_START}")
    lines.append(f"      {SETUP_END}")
    lines.append("")
    lines.append("      - uses: max-sixty/continuous@v1")
    lines.append("        with:")
    lines.append(f"          github_token: {_bot_token(cfg)}")
    lines.append(f"          claude_code_oauth_token: {_claude_token(cfg)}")
    lines.append(f"          bot_name: {cfg.bot_name}")
    lines.append(f'          bot_id: "{cfg.bot_id}"')
    _append_sys_prompt(lines, cfg)
    if "\n" in prompt:
        lines.append("          prompt: |")
        for pline in prompt.split("\n"):
            lines.append(f"            {pline}")
    else:
        lines.append(f"          prompt: \"{prompt}\"")

    lines.append("")
    return GeneratedWorkflow(
        filename=f"cd-{name}.yaml",
        content="\n".join(lines) + "\n",
    )


def generate_nightly(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(cfg, "nightly", "17 6 * * *", "/cd-nightly")


def generate_renovate(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(cfg, "renovate", "17 9 * * 0", "/cd-renovate")


GENERATORS: dict[str, Callable[[Config], GeneratedWorkflow]] = {
    "review": generate_review,
    "mention": generate_mention,
    "triage": generate_triage,
    "ci-fix": generate_ci_fix,
    "nightly": generate_nightly,
    "renovate": generate_renovate,
}


def generate_all(cfg: Config) -> list[GeneratedWorkflow]:
    """Generate all enabled workflows."""
    results = []
    for name, gen_fn in GENERATORS.items():
        wf_cfg = cfg.workflows.get(name, WorkflowConfig())
        if wf_cfg.enabled:
            results.append(gen_fn(cfg))
    return results


def extract_setup_section(content: str) -> str | None:
    """Extract the project setup section from an existing workflow file."""
    start_idx = content.find(SETUP_START)
    end_idx = content.find(SETUP_END)
    if start_idx == -1 or end_idx == -1:
        return None
    # Return everything between the markers (exclusive of markers themselves)
    section = content[start_idx + len(SETUP_START) : end_idx]
    return section


def inject_setup_section(content: str, setup: str) -> str:
    """Replace the project setup section in a workflow file."""
    start_idx = content.find(SETUP_START)
    end_idx = content.find(SETUP_END)
    if start_idx == -1 or end_idx == -1:
        return content
    return content[: start_idx + len(SETUP_START)] + setup + content[end_idx:]
