"""Shared fixtures and configuration for tests."""

from __future__ import annotations

import re

import pytest_regtest


def _normalize_non_latin1(output: str) -> str:
    """Replace non-Latin-1 characters so pytest-regtest's binary check passes.

    pytest-regtest treats characters above U+00FF as "unprintable".
    """
    return output.encode("latin-1", "replace").decode("latin-1")


_HEADER_VERSION = re.compile(r"^# Generated by tend \S+\. Regenerate", re.MULTILINE)


def _scrub_header_version(output: str) -> str:
    """Replace the stamped tend version in the workflow header with a placeholder.

    Snapshots assert structural content, not the literal version — otherwise
    every `version = ...` bump in pyproject.toml would rewrite every regtest
    output. `test_extras_preserve_header` covers the "header starts correctly"
    case separately.
    """
    return _HEADER_VERSION.sub("# Generated by tend X.Y.Z. Regenerate", output)


pytest_regtest.register_converter_pre(_normalize_non_latin1)
pytest_regtest.register_converter_pre(_scrub_header_version)
