"""Behavior tests for nightly_workflow_update.py's persisted lifecycle."""

from __future__ import annotations

import importlib
import json
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[2] / "plugins" / "tend-ci-runner" / "scripts"
sys.path.insert(0, str(SCRIPTS))
nightly = importlib.import_module("nightly_workflow_update")


def _result(
    args: tuple[str, ...], stdout: str = ""
) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(args, 0, stdout, "")


@pytest.fixture
def paths(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict[str, Path]:
    values = {
        "TEND_WORKFLOW_WORKTREE": tmp_path / "worktree",
        "TEND_WORKFLOW_STATE": tmp_path / "state.json",
        "TEND_WORKFLOW_BODY": tmp_path / "body.md",
        "TEND_WORKFLOW_SHA": tmp_path / "sha",
    }
    for key, value in values.items():
        monkeypatch.setenv(key, str(value))
    return values


def test_stamp_only_diff_is_not_a_change() -> None:
    diff = """\
--- a/.github/workflows/tend-review.yaml
+++ b/.github/workflows/tend-review.yaml
-# Generated by tend 1.2.3. Regenerate with: uvx tend@latest init
+# Generated by tend 1.2.4. Regenerate with: uvx tend@latest init
"""

    assert nightly._non_stamp_changes(diff) == 0
    assert (
        nightly._non_stamp_changes(diff + "+uses: max-sixty/tend/claude@1.2.4\n") == 1
    )


def test_prepare_persists_every_value_the_agent_and_ship_need(
    paths: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    calls: list[tuple[tuple[str, ...], Path | None]] = []
    worktree = paths["TEND_WORKFLOW_WORKTREE"]
    paths["TEND_WORKFLOW_BODY"].write_text("stale body\n")
    paths["TEND_WORKFLOW_SHA"].write_text("stale sha\n")

    def run(
        *args: str, cwd: Path | None = None, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        calls.append((args, cwd))
        if args[:3] == ("git", "worktree", "add"):
            workflows = worktree / ".github/workflows"
            workflows.mkdir(parents=True)
            (worktree / ".config").mkdir()
            (workflows / "tend-review.yaml").write_text(
                "# Generated by tend 1.2.3. Regenerate with: uvx tend@latest init\n"
            )
        elif args[:4] == ("uv", "tool", "run", "tend@latest"):
            workflow = worktree / ".github/workflows/tend-review.yaml"
            workflow.write_text(
                "# Generated by tend 1.2.4. Regenerate with: uvx tend@latest init\n"
            )
        if args == ("git", "rev-parse", "FETCH_HEAD"):
            return _result(args, "base\n")
        if args[:3] == ("git", "status", "--porcelain"):
            return _result(args, "M .github/workflows/tend-review.yaml\n")
        if args[:3] == ("git", "diff", "--cached"):
            return _result(args, "+uses: max-sixty/tend/claude@1.2.4\n")
        return _result(args)

    def json_call(*args: str, **_: object) -> object:
        if args[:2] == ("pr", "list"):
            return []
        if args[:2] == ("repo", "view"):
            return {"defaultBranchRef": {"name": "main"}}
        if args[:2] == ("api", "repos/max-sixty/tend/compare/1.2.3...1.2.4"):
            return {"commits": [{"commit": {"message": "Fix the runner\n\nBody"}}]}
        raise AssertionError(args)

    monkeypatch.setattr(nightly, "_run", run)
    monkeypatch.setattr(nightly.github_cli, "json_call", json_call)
    monkeypatch.setattr(nightly.github_cli, "repository", lambda: "owner/repo")

    assert nightly.main(["prepare"]) == 0

    output = json.loads(capsys.readouterr().out)
    assert output == json.loads(paths["TEND_WORKFLOW_STATE"].read_text())
    assert output == {
        "changed": True,
        "worktree": str(worktree),
        "title": "chore: update tend workflows (1.2.3 → 1.2.4)",
        "old_version": "1.2.3",
        "new_version": "1.2.4",
        "compare_url": "https://github.com/max-sixty/tend/compare/1.2.3...1.2.4",
        "upstream_commits": ["Fix the runner"],
        "repository": "owner/repo",
        "existing_pr": None,
    }
    assert not paths["TEND_WORKFLOW_BODY"].exists()
    assert not paths["TEND_WORKFLOW_SHA"].exists()
    assert calls[0][0] == (
        "git",
        "worktree",
        "remove",
        str(worktree),
        "--force",
    )
    worktree_calls = [call for call in calls if call[0][0] in {"uv", "git"}]
    assert any(args[0] == "uv" and cwd == worktree for args, cwd in worktree_calls)
    assert any(
        args[:3] == ("git", "status", "--porcelain") and cwd == worktree
        for args, cwd in worktree_calls
    )


def test_ship_uses_the_prepared_worktree_and_records_its_sha_before_cleanup(
    paths: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    worktree = paths["TEND_WORKFLOW_WORKTREE"]
    worktree.mkdir()
    paths["TEND_WORKFLOW_BODY"].write_text("Automated regeneration.\n")
    paths["TEND_WORKFLOW_STATE"].write_text(
        json.dumps(
            {
                "changed": True,
                "worktree": str(worktree),
                "title": "chore: update tend workflows",
                "repository": "owner/repo",
                "existing_pr": None,
            }
        )
    )
    calls: list[tuple[tuple[str, ...], Path | None]] = []
    sha = "a" * 40

    def run(
        *args: str, cwd: Path | None = None, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        calls.append((args, cwd))
        return _result(args, f"{sha}\n" if args == ("git", "rev-parse", "HEAD") else "")

    monkeypatch.setattr(nightly, "_run", run)
    monkeypatch.setattr(
        nightly.github_cli, "json_call", lambda *args: {"login": "bot", "id": 42}
    )
    gh_calls: list[tuple[str, ...]] = []

    def gh_run(*args: str) -> str:
        gh_calls.append(args)
        return "https://github.com/owner/repo/pull/17\n"

    monkeypatch.setattr(nightly.github_cli, "run", gh_run)
    assert nightly.main(["ship"]) == 0

    assert paths["TEND_WORKFLOW_SHA"].read_text() == f"{sha}\n"
    assert json.loads(capsys.readouterr().out) == {
        "url": "https://github.com/owner/repo/pull/17",
        "number": "17",
        "sha": sha,
    }
    assert gh_calls == [
        (
            "pr",
            "create",
            "--repo",
            "owner/repo",
            "--head",
            nightly.BRANCH,
            "--title",
            "chore: update tend workflows",
            "--body-file",
            str(paths["TEND_WORKFLOW_BODY"]),
        )
    ]
    commit = next(
        i for i, (args, _) in enumerate(calls) if args[:2] == ("git", "commit")
    )
    capture = next(
        i for i, (args, _) in enumerate(calls) if args == ("git", "rev-parse", "HEAD")
    )
    cleanup = next(
        i
        for i, (args, _) in enumerate(calls)
        if args[:3] == ("git", "worktree", "remove")
    )
    assert commit < capture < cleanup
    assert all(
        cwd == worktree for args, cwd in calls if args[:2] != ("git", "worktree")
    )


def test_ship_updates_the_existing_open_pr(
    paths: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    worktree = paths["TEND_WORKFLOW_WORKTREE"]
    worktree.mkdir()
    paths["TEND_WORKFLOW_BODY"].write_text("Updated regeneration.\n")
    paths["TEND_WORKFLOW_STATE"].write_text(
        json.dumps(
            {
                "changed": True,
                "worktree": str(worktree),
                "title": "chore: update tend workflows (1.2.3 → 1.2.4)",
                "repository": "owner/repo",
                "existing_pr": {
                    "number": 17,
                    "url": "https://github.com/owner/repo/pull/17",
                },
            }
        )
    )
    sha = "b" * 40

    def run(
        *args: str, cwd: Path | None = None, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        return _result(args, f"{sha}\n" if args == ("git", "rev-parse", "HEAD") else "")

    monkeypatch.setattr(nightly, "_run", run)
    monkeypatch.setattr(
        nightly.github_cli, "json_call", lambda *args: {"login": "bot", "id": 42}
    )
    gh_calls: list[tuple[str, ...]] = []
    monkeypatch.setattr(
        nightly.github_cli,
        "run",
        lambda *args: gh_calls.append(args) or "",
    )

    assert nightly.main(["ship"]) == 0

    assert gh_calls == [
        (
            "pr",
            "edit",
            "17",
            "--repo",
            "owner/repo",
            "--title",
            "chore: update tend workflows (1.2.3 → 1.2.4)",
            "--body-file",
            str(paths["TEND_WORKFLOW_BODY"]),
        )
    ]
    assert json.loads(capsys.readouterr().out) == {
        "url": "https://github.com/owner/repo/pull/17",
        "number": "17",
        "sha": sha,
    }


def test_prepare_bases_a_fresh_branch_on_the_fetched_default_branch(
    paths: dict[str, Path],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The regen base is the default branch, not whatever the checkout is on.

    Earlier nightly steps open their own PRs from the main checkout with
    `git checkout -b`, so `HEAD` is routinely a survey branch by the time the
    regen runs; basing on it stacks that branch's commits into the
    workflow-update PR.
    """
    calls: list[tuple[tuple[str, ...], Path | None]] = []
    worktree = paths["TEND_WORKFLOW_WORKTREE"]

    def run(
        *args: str, cwd: Path | None = None, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        calls.append((args, cwd))
        if args[:3] == ("git", "worktree", "add"):
            workflows = worktree / ".github/workflows"
            workflows.mkdir(parents=True)
            (worktree / ".config").mkdir()
            (workflows / "tend-review.yaml").write_text(
                "# Generated by tend 1.2.3. Regenerate with: uvx tend@latest init\n"
            )
        elif args[:4] == ("uv", "tool", "run", "tend@latest"):
            (worktree / ".github/workflows/tend-review.yaml").write_text(
                "# Generated by tend 1.2.3. Regenerate with: uvx tend@latest init\n"
                "# uses: max-sixty/tend/claude@1.2.3\n"
            )
        if args == ("git", "rev-parse", "HEAD"):
            return _result(args, "survey-branch-head\n")
        if args == ("git", "rev-parse", "FETCH_HEAD"):
            return _result(args, "default-branch-head\n")
        if args[:3] == ("git", "status", "--porcelain"):
            return _result(args, "M .github/workflows/tend-review.yaml\n")
        if args[:3] == ("git", "diff", "--cached"):
            return _result(args, "+# uses: max-sixty/tend/claude@1.2.3\n")
        return _result(args)

    def json_call(*args: str, **_: object) -> object:
        if args[:2] == ("pr", "list"):
            return []
        if args[:2] == ("repo", "view"):
            return {"defaultBranchRef": {"name": "trunk"}}
        raise AssertionError(args)

    monkeypatch.setattr(nightly, "_run", run)
    monkeypatch.setattr(nightly.github_cli, "json_call", json_call)
    monkeypatch.setattr(nightly.github_cli, "repository", lambda: "owner/repo")

    assert nightly.main(["prepare"]) == 0
    assert json.loads(capsys.readouterr().out)["changed"] is True

    assert ("git", "fetch", "origin", "trunk") in [args for args, _ in calls]
    add = next(args for args, _ in calls if args[:3] == ("git", "worktree", "add"))
    assert add[-1] == "default-branch-head"
