# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Prepare and ship the nightly Tend workflow regeneration.

The two commands bracket the one agent-authored artifact, the PR body. All git
state, version comparison, and temporary-worktree ownership stays in a JSON
state file so separate agent shell calls cannot lose their cwd or variables.
Shipping creates a PR for a fresh update branch or updates the PR already
riding that branch.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import github_cli

BRANCH = "tend/update-workflows"
VERSION_RE = re.compile(r"^# Generated by tend (\d+\.\d+\.\d+)\.")
STAMP_RE = re.compile(
    r"^[+-]# Generated by tend \d+\.\d+\.\d+\. "
    r"Regenerate with: uvx tend@latest init$"
)


def _run(
    *args: str, cwd: Path | None = None, check: bool = True
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        list(args), cwd=cwd, capture_output=True, text=True, check=False
    )
    if check and result.returncode:
        if result.stderr:
            sys.stderr.write(result.stderr)
        raise subprocess.CalledProcessError(
            result.returncode, result.args, result.stdout, result.stderr
        )
    return result


def _paths() -> tuple[Path, Path, Path, Path]:
    return (
        Path(os.environ.get("TEND_WORKFLOW_WORKTREE", "/tmp/tend-update-workflows")),
        Path(os.environ.get("TEND_WORKFLOW_STATE", "/tmp/tend-workflow-update.json")),
        Path(os.environ.get("TEND_WORKFLOW_BODY", "/tmp/tend-update-body.md")),
        Path(os.environ.get("TEND_WORKFLOW_SHA", "/tmp/tend-update-sha")),
    )


def _version(worktree: Path) -> str:
    versions = {
        match.group(1)
        for path in (worktree / ".github/workflows").glob("tend-*.yaml")
        for line in path.read_text().splitlines()
        if (match := VERSION_RE.match(line))
    }
    return min(versions, default="")


def _non_stamp_changes(diff: str) -> int:
    return sum(
        1
        for line in diff.splitlines()
        if line.startswith(("+", "-"))
        and not line.startswith(("+++ ", "--- "))
        and not STAMP_RE.match(line)
    )


def _prepare() -> int:
    worktree, state_path, body_path, sha_path = _paths()
    for artifact in (state_path, body_path, sha_path):
        artifact.unlink(missing_ok=True)
    _run("git", "worktree", "remove", str(worktree), "--force", check=False)
    repo = github_cli.repository()
    open_prs = github_cli.json_call(
        "pr",
        "list",
        "--repo",
        repo,
        "--head",
        BRANCH,
        "--state",
        "open",
        "--json",
        "number,url",
    )
    if open_prs:
        _run("git", "fetch", "origin", BRANCH)
        base = _run("git", "rev-parse", f"origin/{BRANCH}").stdout.strip()
    else:
        _run("git", "push", "origin", "--delete", BRANCH, check=False)
        default = github_cli.json_call(
            "repo", "view", "--repo", repo, "--json", "defaultBranchRef"
        )["defaultBranchRef"]["name"]
        _run("git", "fetch", "origin", default)
        base = _run("git", "rev-parse", "FETCH_HEAD").stdout.strip()

    _run("git", "worktree", "add", str(worktree), "-B", BRANCH, base)
    old_version = _version(worktree)
    _run("uv", "tool", "run", "tend@latest", "init", cwd=worktree)
    _run("git", "add", "-A", ".github", ".config", cwd=worktree)
    status = _run(
        "git", "status", "--porcelain", ".github", ".config", cwd=worktree
    ).stdout
    diff = _run(
        "git",
        "diff",
        "--cached",
        "--no-color",
        "--",
        ".github",
        ".config",
        cwd=worktree,
    ).stdout
    if not status.strip() or _non_stamp_changes(diff) == 0:
        _run("git", "worktree", "remove", str(worktree), "--force")
        github_cli.dump({"changed": False})
        return 0

    new_version = _version(worktree)
    title = "chore: update tend workflows"
    upstream_commits: list[str] = []
    if old_version and new_version and old_version != new_version:
        title += f" ({old_version} → {new_version})"
        try:
            compare = github_cli.json_call(
                "api",
                f"repos/max-sixty/tend/compare/{old_version}...{new_version}",
                quiet=True,
            )
            upstream_commits = [
                str(commit["commit"]["message"]).splitlines()[0]
                for commit in compare["commits"]
            ]
        except (KeyError, TypeError, subprocess.CalledProcessError, ValueError):
            pass

    state: dict[str, Any] = {
        "changed": True,
        "worktree": str(worktree),
        "title": title,
        "old_version": old_version,
        "new_version": new_version,
        "compare_url": (
            f"https://github.com/max-sixty/tend/compare/{old_version}...{new_version}"
            if old_version and new_version and old_version != new_version
            else ""
        ),
        "upstream_commits": upstream_commits,
        "repository": repo,
        "existing_pr": open_prs[0] if open_prs else None,
    }
    state_path.write_text(json.dumps(state, indent=2) + "\n")
    github_cli.dump(state)
    return 0


def _ship() -> int:
    worktree, state_path, body_path, sha_path = _paths()
    state = json.loads(state_path.read_text())
    if state.get("changed") is not True or Path(state.get("worktree", "")) != worktree:
        print("nightly workflow update has no prepared change", file=sys.stderr)
        return 2
    if not body_path.is_file() or not body_path.read_text().strip():
        print(f"write the PR body to {body_path} before shipping", file=sys.stderr)
        return 2

    bot = github_cli.json_call("api", "user")
    login = str(bot["login"])
    bot_id = str(bot["id"])
    _run("git", "config", "--global", "user.name", login, cwd=worktree)
    _run(
        "git",
        "config",
        "--global",
        "user.email",
        f"{bot_id}+{login}@users.noreply.github.com",
        cwd=worktree,
    )
    _run("git", "add", "-A", ".github", ".config", cwd=worktree)
    _run("git", "commit", "-m", str(state["title"]), cwd=worktree)
    _run("git", "push", "-u", "origin", BRANCH, cwd=worktree)
    repo = str(state["repository"])
    existing_pr = state.get("existing_pr")
    if existing_pr:
        number = str(existing_pr["number"])
        github_cli.run(
            "pr",
            "edit",
            number,
            "--repo",
            repo,
            "--title",
            str(state["title"]),
            "--body-file",
            str(body_path),
        )
        url = str(existing_pr["url"])
    else:
        url = github_cli.run(
            "pr",
            "create",
            "--repo",
            repo,
            "--head",
            BRANCH,
            "--title",
            str(state["title"]),
            "--body-file",
            str(body_path),
        ).strip()
        number = url.rstrip("/").rsplit("/", 1)[-1]
    sha = _run("git", "rev-parse", "HEAD", cwd=worktree).stdout.strip()
    sha_path.write_text(f"{sha}\n")
    _run("git", "worktree", "remove", str(worktree), "--force")
    github_cli.dump({"url": url, "number": number, "sha": sha})
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if args == ["prepare"]:
        return _prepare()
    if args == ["ship"]:
        return _ship()
    print(f"usage: {sys.argv[0]} prepare|ship", file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as error:
        raise SystemExit(github_cli.exit_code(error)) from None
