"""Workflow definitions and YAML rendering."""

from __future__ import annotations

import copy
import io
from collections.abc import Callable
from dataclasses import dataclass
from importlib.metadata import version

import click
from ruamel.yaml import YAML

from tend.config import Config, WorkflowConfig

# ruamel.yaml defaults to YAML 1.2, where `on`/`yes`/`no`/`off` are strings,
# not booleans — sidesteps PyYAML's `on:` → True trap and the Norway problem.
# typ="rt" preserves insertion order and per-scalar style (matters for diff
# stability on regen); typ="safe" would sort keys alphabetically.
_YAML_BLOCK = YAML(typ="rt", pure=True)
_YAML_BLOCK.default_flow_style = False
_YAML_BLOCK.width = 200
_YAML_BLOCK.allow_unicode = True
# Round-trip explicit quoting on scalars (e.g. `cron: "17 6 * * *"` stays
# quoted). Without this, ruamel drops quotes on any string that's safe to
# unquote under YAML 1.2 — a meaningless style churn on regen.
_YAML_BLOCK.preserve_quotes = True
# Match the hand-rendered templates' 6-space `- uses:` under `steps:` (the
# `-` lives at parent-column + offset, the content at parent-column +
# sequence). Without this, `_apply_extras`-applied workflows reformat every
# step block (4→6 column for `-`, 4→8 for content) on regen — a churn diff
# for any consumer with `workflow_extra` or per-job overrides.
_YAML_BLOCK.indent(mapping=2, sequence=4, offset=2)

_YAML_FLOW = YAML(typ="safe", pure=True)
_YAML_FLOW.default_flow_style = True
_YAML_FLOW.allow_unicode = True
_YAML_FLOW.width = 10**9  # one-line scalars; never wrap

# Stamping the generator's own version into the header gives downstream
# nightly regen a stable anchor for detecting tend version bumps (see
# plugins/tend-ci-runner/skills/nightly/SKILL.md, Step 6) regardless of what
# templates pin for `uvx tend@...` or the action tag.
HEADER = f"""\
# Generated by tend {version("tend")}. Regenerate with: uvx tend@latest init
#
# Do not edit this file directly — it will be overwritten on regeneration.
# To customize behavior, edit the relevant skill (for example,
# `running-tend`) in this repo's .claude/skills/ directory, or open an issue at
# https://github.com/max-sixty/tend/issues for changes that need to
# happen upstream in the tend-ci-runner plugin.
"""


def _bot_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.bot_token_secret} }}}}"


def _claude_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.claude_token_secret} }}}}"


def _openai_key(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.openai_key_secret} }}}}"


def _codex_auth_json(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.codex_auth_json_secret} }}}}"


def _default_prompt(cfg: Config, skill: str, args_template: str = "") -> str:
    """Default prompt invoking a tend-ci-runner skill in engine-native syntax.

    Claude resolves `/tend-ci-runner:NAME` as a slash command. Codex resolves
    `$NAME` as a skill mention (or matches by description); the
    `tend-ci-runner` namespace prefix isn't needed at the prompt site because
    skill names within the plugin are unique. `args_template` is appended
    raw so callers can splice their own placeholders (`{pr_number}`,
    `{issue_number}`, etc.) and run the existing replace step.
    """
    invocation = f"/tend-ci-runner:{skill}" if cfg.engine == "claude" else f"${skill}"
    return f"{invocation} {args_template}".rstrip()


def _action_ref(cfg: Config) -> str:
    """Ref string for the engine-specific composite action.

    Both actions ship from this repo; the Codex variant lives under /codex/.
    Pinned to v1; release tags promote both action paths together.
    """
    return "max-sixty/tend@v1" if cfg.engine == "claude" else "max-sixty/tend/codex@v1"


def _agent_step(
    cfg: Config,
    prompt_body: str,
    *,
    indent: int = 6,
    use_sticky_comment: bool = False,
    if_condition: str = "",
) -> str:
    """Render the `uses: max-sixty/tend@v1` step.

    `prompt_body` is the rendered prompt value (everything after `prompt:`),
    including any leading whitespace. Callers handle the prompt's YAML shape
    (block scalar `|`, folded `>-`, expression-quoted single line) — this
    helper just splices it under `with:`.
    """
    pad = " " * indent
    bt = _bot_token(cfg)
    bn = cfg.bot_name
    ref = _action_ref(cfg)

    lines = [f"{pad}- uses: {ref}"]
    if if_condition:
        lines.append(f"{pad}  if: {if_condition}")
    lines.append(f"{pad}  with:")
    lines.append(f"{pad}    github_token: {bt}")

    if cfg.engine == "claude":
        ct = _claude_token(cfg)
        lines.append(f"{pad}    claude_code_oauth_token: {ct}")
    else:
        # Emit both Codex auth inputs unconditionally; the codex action picks
        # auth.json over api-key when both are configured. Adopters set just
        # the one they want — the other renders as an empty string.
        lines.append(f"{pad}    openai_api_key: {_openai_key(cfg)}")
        lines.append(f"{pad}    codex_auth_json: {_codex_auth_json(cfg)}")
        if cfg.effort:
            lines.append(f"{pad}    effort: {cfg.effort}")

    lines.append(f"{pad}    bot_name: {bn}")
    lines.append(f"{pad}    model: {cfg.model}")
    if use_sticky_comment and cfg.engine == "claude":
        # Codex action posts via gh from inside skill prompts; no sticky.
        lines.append(f"{pad}    use_sticky_comment: true")
    lines.append(f"{pad}    {prompt_body}")
    return "\n".join(lines)


_STEP_FIELD_ORDER = [
    "uses",
    "run",
    "name",
    "id",
    "if",
    "shell",
    "working-directory",
    "continue-on-error",
    "timeout-minutes",
    "with",
    "env",
]
# Scalar fields where we want plain (unquoted) YAML emission, matching the
# existing style of generated workflows and letting GitHub Actions expressions
# pass through unescaped.
_PLAIN_TOP_LEVEL = {
    "uses",
    "run",
    "if",
    "name",
    "id",
    "shell",
    "working-directory",
}


def _setup_yaml(cfg: Config, indent: int = 6, condition: str = "") -> str:
    """Render setup steps as YAML, indented to `indent` spaces.

    Returns empty string when no steps, or newline-prefixed block when present,
    so templates can write `{setup}` without extra blank lines.

    When *condition* is set, steps without an explicit `if:` receive one so
    they only run when the pre-check found work. Steps that already specify
    `if:` are left alone (with a warning) — their condition wins.
    """
    lines = []
    for step in cfg.setup:
        fields = dict(step.fields)
        if condition:
            if "if" in fields:
                click.echo(
                    "Warning: setup step has an explicit `if:`; the "
                    "notifications pre-check guard will not be added. "
                    "The step runs based on your condition alone.",
                    err=True,
                )
            else:
                fields["if"] = condition
        lines.append(_render_step(_order_step_fields(fields), indent))
    if not lines:
        return ""
    return "\n" + "\n".join(lines) + "\n"


def _order_step_fields(fields: dict) -> dict:
    """Emit keys in a stable order: step kind first, then metadata, then tables."""
    ordered = {k: fields[k] for k in _STEP_FIELD_ORDER if k in fields}
    for k, v in fields.items():
        if k not in ordered:
            ordered[k] = v
    return ordered


def _render_step(fields: dict, indent: int) -> str:
    """Render a step dict as a YAML list item at the given indent column."""
    pad = " " * indent
    lines = []
    for i, (key, value) in enumerate(fields.items()):
        prefix = f"{pad}- " if i == 0 else f"{pad}  "
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            for sk, sv in value.items():
                lines.append(f"{pad}    {sk}: {_yaml_scalar(sv)}")
        elif key in _PLAIN_TOP_LEVEL:
            lines.append(f"{prefix}{key}: {value}")
        else:
            lines.append(f"{prefix}{key}: {_yaml_scalar(value)}")
    return "\n".join(lines)


def _yaml_scalar(value: object) -> str:
    """Render a Python scalar as a single-line YAML scalar."""
    buf = io.StringIO()
    _YAML_FLOW.dump(value, buf)
    # ruamel emits a trailing newline; strip and drop any `...` document marker.
    dumped = buf.getvalue().rstrip()
    if dumped.endswith("\n..."):
        dumped = dumped[: -len("\n...")]
    return dumped


def _fork_guard(cfg: Config) -> str:
    """`if:` expression that skips a job when running outside the canonical owner.

    Compares `github.repository_owner` against the configured owner: `secrets`
    isn't available in `jobs.<job_id>.if`, and `github.event.repository.fork`
    is null for `schedule` events, so the owner string is the only check that
    works across all the affected event types. Returns "" if the owner is
    unknown — callers omit the guard rather than fail.
    """
    if not cfg.repo_owner:
        return ""
    return f"github.repository_owner == '{_escape(cfg.repo_owner)}'"


def _permissions(issues: bool = True) -> str:
    lines = [
        "      contents: write",
        "      pull-requests: write",
        "      id-token: write",
        "      actions: read",
    ]
    if issues:
        lines.append("      issues: write")
    return "\n".join(lines)


def _escape(s: str) -> str:
    """Escape single quotes for GitHub Actions expressions."""
    return s.replace("'", "''")


@dataclass
class GeneratedWorkflow:
    filename: str
    content: str


# ---------------------------------------------------------------------------
# Review
# ---------------------------------------------------------------------------


def _escape_braces(prompt: str, placeholder: str) -> tuple[str, bool]:
    """Escape literal braces in a prompt, preserving only {placeholder}.

    Returns (escaped_prompt, needs_format). In the escaped prompt, {placeholder}
    is replaced with {0} for use with GitHub Actions format(), and all other
    braces are doubled to prevent format() from interpreting them.
    """
    sentinel = "\x00PLACEHOLDER\x00"
    text = prompt.replace(f"{{{placeholder}}}", sentinel)
    # Double all remaining braces so format() treats them as literals
    text = text.replace("{", "{{").replace("}", "}}")
    has_placeholder = sentinel in text
    text = text.replace(sentinel, "{0}")
    return text, has_placeholder


def generate_review(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("review", WorkflowConfig())
    raw_prompt = wf.prompt or _default_prompt(cfg, "review", "{pr_number}")
    format_body, needs_format = _escape_braces(raw_prompt, "pr_number")
    escaped = _escape(format_body)
    if needs_format:
        prompt_expr = f"format('{escaped}', github.event.pull_request.number)"
    else:
        prompt_expr = f"'{escaped}'"

    bt = _bot_token(cfg)

    setup = _setup_yaml(cfg)
    perms = _permissions()
    agent = _agent_step(
        cfg,
        f"prompt: >-\n            ${{{{ {prompt_expr} }}}}",
        use_sticky_comment=True,
    )

    content = f"""\
{HEADER}
name: tend-review
on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  review:
    concurrency:
      group: ${{{{ github.workflow }}}}-${{{{ github.event.pull_request.number }}}}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      # GitHub only materializes refs/pull/N/merge for mergeable PRs — on
      # conflicting PRs it 404s and every downstream step cascades as skipped.
      # Probe first and fall back to /head so review always runs; on fallback
      # the review sees the PR branch in isolation rather than the post-merge
      # tree.
      - name: Resolve PR checkout ref
        id: pr_ref
        env:
          GITHUB_TOKEN: {bt}
          PR: ${{{{ github.event.pull_request.number }}}}
        run: |
          if gh api "repos/${{{{ github.repository }}}}/git/ref/pull/$PR/merge" --silent 2>/dev/null; then
            echo "ref=refs/pull/$PR/merge" >> "$GITHUB_OUTPUT"
          else
            echo "ref=refs/pull/$PR/head" >> "$GITHUB_OUTPUT"
            echo "::notice::refs/pull/$PR/merge unavailable (likely merge conflict); falling back to /head"
          fi
      - uses: actions/checkout@v6
        with:
          ref: ${{{{ steps.pr_ref.outputs.ref }}}}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
{agent}
"""
    return GeneratedWorkflow(filename="tend-review.yaml", content=content)


# ---------------------------------------------------------------------------
# Mention
# ---------------------------------------------------------------------------


def generate_mention(cfg: Config) -> GeneratedWorkflow:
    bt = _bot_token(cfg)
    bn = cfg.bot_name

    setup = _setup_yaml(cfg)
    perms = _permissions()
    pr = "(github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number)"

    # Continuation lines inside a folded `>-` scalar are indented one level
    # deeper than the `prompt:` key. The agent step renders fields at column
    # `indent + 4` (10 with indent=6); continuation goes at column 12.
    prompt_body = (
        f"prompt: >-\n"
        f"            ${{{{ steps.delay.outputs.seconds\n"
        f"            && format('This job started {{0}}s after the triggering event (over ~40s means it was queued). ',\n"
        f"            steps.delay.outputs.seconds) || '' }}}}Before acting,\n"
        f"            check recent comments: exit silently if the bot already responded\n"
        f"            to the trigger; handle any other unaddressed comments too.\n"
        f"\n"
        f"            ${{{{ github.event_name == 'issues'\n"
        f"              && format('An issue was updated with a mention of you ({{0}}). Read it and respond.', github.event.issue.html_url)\n"
        f"              || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@{bn}')\n"
        f"                && format('You were mentioned in an inline review comment on PR #{{0}} ({{1}}, comment ID {{2}}). Read the full context, then respond. If changes are requested, make them, commit, and push.', {pr}, github.event.comment.html_url, github.event.comment.id))\n"
        f"              || (github.event_name == 'pull_request_review_comment'\n"
        f"                && format('An inline review comment was posted on a PR where you previously participated (PR #{{0}}, {{1}}, comment ID {{2}}). Read the full context. Only respond if the comment is directed at you or requests changes.', {pr}, github.event.comment.html_url, github.event.comment.id))\n"
        f"              || (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@{bn}')\n"
        f"                && format('A review was submitted on PR #{{0}} that mentions you ({{1}}, review ID {{2}}). Read the review and full context, then respond. If changes were requested, make them, commit, and push.', github.event.pull_request.number, github.event.review.html_url, github.event.review.id))\n"
        f"              || (github.event_name == 'pull_request_review'\n"
        f"                && format('A review was submitted on a PR where you previously participated (PR #{{0}}, {{1}}, review ID {{2}}). Read the review and full context. If the review requests changes or asks questions, respond appropriately. If the review approves or is between humans, exit silently.', github.event.pull_request.number, github.event.review.html_url, github.event.review.id))\n"
        f"              || (contains(github.event.comment.body, '@{bn}')\n"
        f"                && format('You were mentioned in a comment ({{0}}). Read the full context and respond. If changes are requested, make them, commit, and push.', github.event.comment.html_url))\n"
        f"              || format('A user commented on an issue/PR where you previously participated ({{0}}). Read the full context. Only respond if the comment is directed at you, asks a question you can help with, or requests changes you can make. If the conversation is between other participants, exit silently.', github.event.comment.html_url)\n"
        f"            }}}}"
    )
    agent = _agent_step(cfg, prompt_body)

    content = f"""\
{HEADER}
name: tend-mention
on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]
  # Works for same-repo PRs only; secrets unavailable on fork PRs (no _target variant exists)
  pull_request_review:
    types: [submitted]
  # `created` is intentionally absent. Modern GitHub fires *both*
  # pull_request_review and pull_request_review_comment for every newly-created
  # inline comment (the standalone POST /pulls/PR/comments endpoint, the
  # /replies endpoint, the "Add single comment" UI button, and reviews
  # submitted with inline comments — all empirically verified). Subscribing to
  # `created` would produce a duplicate workflow run that collides on the
  # tend-mention-handle-PR concurrency group, with the loser cancelled and
  # posted as a CANCELLED check_run on the PR head SHA — which renders the
  # PR's statusCheckRollup as FAILURE even though the bot did its job from the
  # sibling run. Edits have no sibling event (review submissions don't fire on
  # edits), so we still need to listen for `edited` to catch edit-to-summon
  # ("@bot" added to an existing comment after the fact).
  pull_request_review_comment:
    types: [edited]

jobs:
  verify:
    # Filter out fork PRs for review events — secrets are unavailable there
    # (no _target variant exists). The notifications workflow polls for these.
    # Skip comments on `tend-outage` issues: the action's Report-failure step
    # auto-comments on those when Claude invocation fails, and without this
    # guard those comments re-trigger tend-mention during a persistent outage
    # (e.g. Anthropic 401), producing a self-sustaining ~1 run/minute loop
    # until the outage clears. The prompt's self-loop guard can't help here
    # because the model never executes — the action fails before Claude starts.
    if: |
      (github.event_name == 'issues' &&
        contains(github.event.issue.body, '@{bn}')) ||
      (github.event_name == 'issue_comment' &&
        !contains(github.event.issue.labels.*.name, 'tend-outage')) ||
      (github.event_name == 'pull_request_review_comment' &&
        github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_review' &&
        github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-24.04
    outputs:
      should_run: ${{{{ steps.check.outputs.should_run }}}}
    steps:
      - name: Verify bot engagement
        id: check
        run: |
          # Mentions always run
          if [ "$EVENT_NAME" = "issues" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ -n "$COMMENT_BODY" ] && printf '%s\\n' "$COMMENT_BODY" | grep -qF '@{bn}'; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # pull_request_review payloads include review.body (checked above)
          # but NOT the bodies of inline comments attached to the review.
          # Fetch them so a first-contact @-mention inside an inline comment
          # is detected on PRs where the bot has no prior engagement.
          if [ "$EVENT_NAME" = "pull_request_review" ] && [ -n "$REVIEW_ID" ]; then
            if gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$EVENT_PR_NUMBER/reviews/$REVIEW_ID/comments" \\
                 --jq '.[].body' | grep -qF '@{bn}'; then
              echo "should_run=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          # Non-mention: check bot engagement
          if [ "$EVENT_NAME" = "issue_comment" ]; then
            ISSUE_NUMBER="$ISSUE_OR_PR_NUMBER"

            if [ -z "$PR_URL" ]; then
              if [ "$ISSUE_AUTHOR" = "{bn}" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              if printf '%s\\n' "$ISSUE_BODY" | grep -qF '@{bn}'; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              BOT_COMMENTS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \\
                --jq '[.[] | select(.user.login == "{bn}")] | length')
              if [ "$BOT_COMMENTS" -gt "0" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              echo "should_run=false" >> "$GITHUB_OUTPUT"; exit 0
            fi

            PR_NUMBER="$ISSUE_NUMBER"
          else
            PR_NUMBER="$EVENT_PR_NUMBER"
          fi

          PR_AUTHOR=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json author --jq '.author.login')
          if [ "$PR_AUTHOR" = "{bn}" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_REVIEWS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \\
            --jq '[.[] | select(.user.login == "{bn}")] | length')
          if [ "$BOT_REVIEWS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_COMMENTS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \\
            --jq '[.[] | select(.user.login == "{bn}")] | length')
          if [ "$BOT_COMMENTS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          echo "should_run=false" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: {bt}
          EVENT_NAME: ${{{{ github.event_name }}}}
          COMMENT_BODY: ${{{{ github.event.comment.body || github.event.review.body }}}}
          ISSUE_BODY: ${{{{ github.event.issue.body }}}}
          ISSUE_OR_PR_NUMBER: ${{{{ github.event.issue.number }}}}
          ISSUE_AUTHOR: ${{{{ github.event.issue.user.login }}}}
          PR_URL: ${{{{ github.event.issue.pull_request.url }}}}
          EVENT_PR_NUMBER: ${{{{ github.event.pull_request.number }}}}
          REVIEW_ID: ${{{{ github.event.review.id }}}}

      - name: React to mention
        if: |
          steps.check.outputs.should_run == 'true'
          && github.event.comment
          && contains(github.event.comment.body, '@{bn}')
        run: |
          gh api "repos/$REPO/issues/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || \\
          gh api "repos/$REPO/pulls/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || true
        env:
          REPO: ${{{{ github.repository }}}}
          COMMENT_ID: ${{{{ github.event.comment.id }}}}
          GITHUB_TOKEN: {bt}

  handle:
    needs: verify
    if: needs.verify.outputs.should_run == 'true'
    concurrency:
      group: ${{{{ github.workflow }}}}-handle-${{{{ github.event.issue.number || github.event.pull_request.number }}}}
      cancel-in-progress: false
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
      - name: Check out PR branch
        if: |
          (github.event_name == 'issue_comment' && github.event.issue.pull_request.url != '') ||
          github.event_name == 'pull_request_review_comment' ||
          github.event_name == 'pull_request_review'
        run: |
          PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq '.state')
          if [ "$PR_STATE" = "OPEN" ]; then
            gh pr checkout "$PR_NUMBER"
          else
            echo "::warning::PR is $PR_STATE — staying on default branch"
          fi
        env:
          GITHUB_TOKEN: {bt}
          PR_NUMBER: ${{{{ github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number }}}}

      - name: Compute queue delay
        id: delay
        run: |
          if [ -z "$EVENT_TS" ]; then
            echo "seconds=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          event_epoch=$(date -d "$EVENT_TS" +%s)
          echo "seconds=$(( $(date +%s) - event_epoch ))" >> "$GITHUB_OUTPUT"
        env:
          EVENT_TS: ${{{{ github.event.comment.created_at || github.event.review.submitted_at || github.event.issue.updated_at }}}}

{agent}
"""
    return GeneratedWorkflow(filename="tend-mention.yaml", content=content)


# ---------------------------------------------------------------------------
# Triage
# ---------------------------------------------------------------------------


def generate_triage(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("triage", WorkflowConfig())
    prompt = (wf.prompt or _default_prompt(cfg, "triage", "{issue_number}")).replace(
        "{issue_number}", "${{ github.event.issue.number }}"
    )
    bt = _bot_token(cfg)

    setup = _setup_yaml(cfg)
    perms = _permissions()
    guard = _fork_guard(cfg)
    if_block = f"\n    if: {guard}" if guard else ""
    agent = _agent_step(cfg, f"prompt: |\n            {prompt}")

    content = f"""\
{HEADER}
name: tend-triage
on:
  issues:
    types: [opened]

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.event.issue.number }}}}
  cancel-in-progress: true

jobs:
  triage:{if_block}
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {cfg.default_branch}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
{agent}
"""
    return GeneratedWorkflow(filename="tend-triage.yaml", content=content)


# ---------------------------------------------------------------------------
# CI Fix
# ---------------------------------------------------------------------------


def generate_ci_fix(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("ci-fix", WorkflowConfig())
    if wf.watched_workflows is None:
        raise click.ClickException(
            "ci-fix requires watched_workflows — specify the CI workflow(s) to monitor.\n\n"
            "  workflows:\n"
            "    ci-fix:\n"
            '      watched_workflows: ["ci"]'
        )
    watched = wf.watched_workflows
    branches = wf.branches if wf.branches is not None else [cfg.default_branch]
    prompt = (wf.prompt or _default_prompt(cfg, "ci-fix", "{run_id}")).replace(
        "{run_id}", "${{ github.event.workflow_run.id }}"
    )
    bt = _bot_token(cfg)

    setup = _setup_yaml(cfg)
    perms = _permissions(issues=False)
    watched_yaml = ", ".join(f'"{w}"' for w in watched)
    branches_yaml = ", ".join(f'"{b}"' for b in branches)
    conclusion_check = "github.event.workflow_run.conclusion == 'failure'"
    guard = _fork_guard(cfg)
    guard_if = f"{guard} && {conclusion_check}" if guard else conclusion_check
    agent = _agent_step(
        cfg,
        f"prompt: |\n            {prompt}\n"
        f"            - Run URL: ${{{{ github.event.workflow_run.html_url }}}}\n"
        f"            - Commit: ${{{{ github.event.workflow_run.head_sha }}}}\n"
        f"            - Commit message: ${{{{ github.event.workflow_run.head_commit.message }}}}",
    )

    content = f"""\
{HEADER}
name: tend-ci-fix
on:
  workflow_run:
    workflows: [{watched_yaml}]
    types: [completed]
    branches: [{branches_yaml}]

jobs:
  fix-ci:
    if: {guard_if}
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {cfg.default_branch}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
{agent}
"""
    return GeneratedWorkflow(filename="tend-ci-fix.yaml", content=content)


# ---------------------------------------------------------------------------
# Scheduled (nightly, weekly)
# ---------------------------------------------------------------------------


def _generate_scheduled(
    cfg: Config, name: str, default_cron: str, default_prompt: str
) -> GeneratedWorkflow:
    wf = cfg.workflows.get(name, WorkflowConfig())
    cron = wf.cron or default_cron
    prompt = wf.prompt or default_prompt
    bt = _bot_token(cfg)

    setup = _setup_yaml(cfg)
    perms = _permissions()
    guard = _fork_guard(cfg)
    if_block = f"\n    if: {guard}" if guard else ""

    prompt_lines = "\n".join(f"            {line}" for line in prompt.split("\n"))
    agent = _agent_step(cfg, f"prompt: |\n{prompt_lines}")

    content = f"""\
{HEADER}
name: tend-{name}
on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:

jobs:
  {name}:{if_block}
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {cfg.default_branch}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
{agent}
"""
    return GeneratedWorkflow(filename=f"tend-{name}.yaml", content=content)


# Default cron times target Anthropic's off-peak hours (outside weekday
# 8am–2pm ET / 12:00–18:00 UTC). Non-round minutes avoid thundering herd.


def generate_nightly(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(
        cfg, "nightly", "17 6 * * *", _default_prompt(cfg, "nightly")
    )


def generate_weekly(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(
        cfg, "weekly", "17 9 * * 0", _default_prompt(cfg, "weekly")
    )


def generate_notifications(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("notifications", WorkflowConfig())
    cron = wf.cron or "*/15 * * * *"
    prompt = wf.prompt or _default_prompt(cfg, "notifications")
    bt = _bot_token(cfg)
    bn = cfg.bot_name

    skip_condition = (
        "steps.check.outputs.count != '0' || github.event_name == 'workflow_dispatch'"
    )
    setup = _setup_yaml(cfg, condition=skip_condition)
    perms = _permissions()
    guard = _fork_guard(cfg)
    if_block = f"\n    if: {guard}" if guard else ""

    prompt_lines = "\n".join(f"            {line}" for line in prompt.split("\n"))
    agent = _agent_step(cfg, f"prompt: |\n{prompt_lines}", if_condition=skip_condition)

    content = f"""\
{HEADER}
name: tend-notifications
on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:

jobs:
  notifications:{if_block}
    runs-on: ubuntu-24.04
    permissions:
{perms}
    steps:
      - name: Check for unread notifications
        id: check
        run: |
          COUNT=$(gh api notifications --jq 'length')
          if [ "$COUNT" = "0" ]; then
            echo "count=0" >> "$GITHUB_OUTPUT"
            echo "No unread notifications — skipping"
            exit 0
          fi

          # --- Layer B: drop notifications shadowed by recent dedicated runs ---
          # Event workflows mark their own notifications read via action.yaml's
          # post-step on success; this sweeps the case where Claude failed
          # (post-step is gated by `if: success()`) so the notification still
          # gets cleared without burning Claude turns to rediscover it.
          SINCE=$(date -u -d '30 minutes ago' +%Y-%m-%dT%H:%M:%SZ)
          RECENT_PRS=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs?created=>=$SINCE&per_page=50" --jq '[.workflow_runs[] | select(.name | test("^(tend-review|tend-mention|tend-triage|tend-ci-fix)$")) | .pull_requests[]?.number] | unique | .[]' || true)

          if [ -n "$RECENT_PRS" ]; then
            NOTIFS=$(gh api notifications)
            for pr in $RECENT_PRS; do
              echo "$NOTIFS" | jq -r --arg repo "$GITHUB_REPOSITORY" --arg pr "$pr" '.[] | select(.subject.url == "https://api.github.com/repos/" + $repo + "/pulls/" + $pr or .subject.url == "https://api.github.com/repos/" + $repo + "/issues/" + $pr) | .id' | while read -r tid; do
                [ -n "$tid" ] || continue
                gh api "notifications/threads/$tid" -X PATCH || true
              done
            done
          fi

          # --- Layer C: drop notifications on bot-authored closed PRs ---
          # The bot auto-subscribes to its own PRs. After merge/close, leftover
          # subscription notifications are pure noise — no action needed.
          NOTIFS=$(gh api notifications)
          echo "$NOTIFS" | jq -r --arg repo "$GITHUB_REPOSITORY" '.[] | select(.repository.full_name == $repo and .subject.type == "PullRequest") | .id' | while read -r tid; do
            [ -n "$tid" ] || continue
            PR_NUM=$(echo "$NOTIFS" | jq -r --arg tid "$tid" '.[] | select(.id == $tid) | .subject.url | split("/") | last')
            PR_INFO=$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUM" --jq '"\\(.user.login) \\(.state)"' 2>/dev/null) || continue
            PR_AUTHOR=${{PR_INFO%% *}}
            PR_STATE=${{PR_INFO##* }}
            if [ "$PR_AUTHOR" = "{bn}" ] && [ "$PR_STATE" = "closed" ]; then
              gh api "notifications/threads/$tid" -X PATCH || true
            fi
          done

          # --- Layer D: count processable notifications ---
          # Same-repo notifications younger than 10 minutes are deferred: a
          # dedicated workflow (tend-review/mention/triage/ci-fix) is likely
          # still starting up or mid-flight and hasn't posted its response yet.
          # Processing them now risks duplicating work. Cross-repo notifications
          # are exempt — no dedicated workflow handles them.
          CUTOFF=$(date -u -d '10 minutes ago' +%Y-%m-%dT%H:%M:%SZ)
          REMAINING=$(gh api notifications)
          COUNT=$(echo "$REMAINING" | jq --arg repo "$GITHUB_REPOSITORY" --arg cutoff "$CUTOFF" '[.[] | select(.repository.full_name != $repo or .updated_at <= $cutoff)] | length')
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          if [ "$COUNT" = "0" ]; then
            TOTAL=$(echo "$REMAINING" | jq 'length')
            if [ "$TOTAL" = "0" ]; then
              echo "All notifications handled by pre-checks — skipping"
            else
              echo "$TOTAL notification(s) remain but all are fresh same-repo (deferred) — skipping"
            fi
          else
            echo "$COUNT processable notification(s) — proceeding"
          fi
        env:
          GITHUB_TOKEN: {bt}

      - uses: actions/checkout@v6
        if: {skip_condition}
        with:
          ref: {cfg.default_branch}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}\
{agent}
"""
    return GeneratedWorkflow(filename="tend-notifications.yaml", content=content)


def generate_review_runs(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(
        cfg, "review-runs", "47 7 * * *", _default_prompt(cfg, "review-runs")
    )


# ---------------------------------------------------------------------------
# Extras (workflow_extra / jobs pass-through)
# ---------------------------------------------------------------------------


def _deep_merge(base: dict, override: dict) -> dict:
    """RFC 7396 JSON Merge Patch: mappings deep-merge, scalars/lists replace.

    `base` is deep-copied so ruamel.yaml `CommentedMap` style metadata
    (key order, scalar quoting, sequence indentation) survives the merge —
    without this, `_apply_extras`-applied workflows lose all rendering
    style on every regen, even for keys the user didn't override.
    """
    result = copy.deepcopy(base)
    for key, value in override.items():
        if value is None:
            result.pop(key, None)
        elif isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _apply_extras(wf: GeneratedWorkflow, wf_cfg: WorkflowConfig) -> GeneratedWorkflow:
    """Merge workflow_extra and per-job extras into rendered YAML (RFC 7396)."""
    if not wf_cfg.workflow_extra and not wf_cfg.jobs:
        return wf

    data = _YAML_BLOCK.load(wf.content)

    if wf_cfg.workflow_extra:
        data = _deep_merge(data, wf_cfg.workflow_extra)

    if wf_cfg.jobs:
        jobs = data.get("jobs", {})
        for job_name, job_extra in wf_cfg.jobs.items():
            if job_name in jobs:
                jobs[job_name] = _deep_merge(jobs[job_name], job_extra)
            else:
                click.echo(
                    f"Warning: job '{job_name}' not found in {wf.filename} "
                    f"(known: {', '.join(sorted(jobs))})",
                    err=True,
                )

    # `typ="rt"` preserves the leading HEADER comment block on load, so it
    # round-trips into the dumped output. Don't prepend HEADER manually
    # here or it appears twice.
    buf = io.StringIO()
    _YAML_BLOCK.dump(data, buf)
    return GeneratedWorkflow(filename=wf.filename, content=buf.getvalue())


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

GENERATORS: dict[str, Callable[[Config], GeneratedWorkflow]] = {
    "review": generate_review,
    "mention": generate_mention,
    "triage": generate_triage,
    "ci-fix": generate_ci_fix,
    "nightly": generate_nightly,
    "weekly": generate_weekly,
    "notifications": generate_notifications,
    "review-runs": generate_review_runs,
}


def generate_all(cfg: Config) -> list[GeneratedWorkflow]:
    """Generate all enabled workflows."""
    results = []
    for name, gen_fn in GENERATORS.items():
        wf_cfg = cfg.workflows.get(name, WorkflowConfig())
        if not wf_cfg.enabled:
            continue
        if name == "ci-fix" and wf_cfg.watched_workflows is None:
            click.echo(
                "Skipping ci-fix: watched_workflows not configured. "
                "To enable, add to .config/tend.yaml:\n\n"
                "  workflows:\n"
                "    ci-fix:\n"
                '      watched_workflows: ["ci"]',
                err=True,
            )
            continue
        wf = gen_fn(cfg)
        wf = _apply_extras(wf, wf_cfg)
        results.append(wf)
    return results
