"""Workflow definitions and YAML rendering."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from tend.config import Config, WorkflowConfig

HEADER = "# Generated by tend. Regenerate with: uvx tend init\n"


def _bot_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.bot_token_secret} }}}}"


def _claude_token(cfg: Config) -> str:
    return f"${{{{ secrets.{cfg.claude_token_secret} }}}}"


def _setup_yaml(cfg: Config, indent: int = 6) -> str:
    """Render setup steps as YAML, indented to `indent` spaces.

    Returns empty string when no steps, or newline-prefixed block when present,
    so templates can write `{setup}` without extra blank lines.
    """
    pad = " " * indent
    lines = []
    for step in cfg.setup:
        if step.uses:
            lines.append(f"{pad}- uses: {step.uses}")
        elif step.run:
            lines.append(f"{pad}- run: {step.run}")
    if not lines:
        return ""
    return "\n" + "\n".join(lines) + "\n"


def _permissions(issues: bool = True) -> str:
    lines = [
        "      contents: write",
        "      pull-requests: write",
        "      id-token: write",
        "      actions: read",
    ]
    if issues:
        lines.append("      issues: write")
    return "\n".join(lines)


def _escape(s: str) -> str:
    """Escape single quotes for GitHub Actions expressions."""
    return s.replace("'", "''")


@dataclass
class GeneratedWorkflow:
    filename: str
    content: str


# ---------------------------------------------------------------------------
# Review
# ---------------------------------------------------------------------------

def _escape_braces(prompt: str, placeholder: str) -> tuple[str, bool]:
    """Escape literal braces in a prompt, preserving only {placeholder}.

    Returns (escaped_prompt, needs_format). In the escaped prompt, {placeholder}
    is replaced with {0} for use with GitHub Actions format(), and all other
    braces are doubled to prevent format() from interpreting them.
    """
    sentinel = "\x00PLACEHOLDER\x00"
    text = prompt.replace(f"{{{placeholder}}}", sentinel)
    # Double all remaining braces so format() treats them as literals
    text = text.replace("{", "{{").replace("}", "}}")
    has_placeholder = sentinel in text
    text = text.replace(sentinel, "{0}")
    return text, has_placeholder


def generate_review(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("review", WorkflowConfig())
    raw_prompt = wf.prompt or "/tend:tend-review {pr_number}"
    format_body, needs_format = _escape_braces(raw_prompt, "pr_number")
    escaped = _escape(format_body)
    if needs_format:
        prompt_expr = f"format('{escaped}', github.event.pull_request.number)"
    else:
        prompt_expr = f"'{escaped}'"

    bt = _bot_token(cfg)
    ct = _claude_token(cfg)
    bn = cfg.bot_name

    setup = _setup_yaml(cfg)
    perms = _permissions()

    content = f"""\
{HEADER}
name: tend-review
on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  review:
    if: |
      (github.event_name == 'pull_request_target' &&
        github.event.pull_request.draft == false) ||
      (github.event_name == 'pull_request_review' &&
        github.event.pull_request.user.login == '{bn}' &&
        github.event.review.user.login != '{bn}' &&
        (github.event.review.state != 'approved' || github.event.review.body))
    concurrency:
      group: ${{{{ github.workflow }}}}-${{{{ github.event_name }}}}-${{{{ github.event.pull_request.number }}}}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
{perms}
    steps:
      - name: Checkout (initial review)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v6
        with:
          ref: refs/pull/${{{{ github.event.pull_request.number }}}}/merge
          fetch-depth: 0
          fetch-tags: true
          token: {bt}

      - name: Checkout (review response)
        if: github.event_name == 'pull_request_review'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          token: {bt}

      - name: Check out PR branch (review response)
        if: github.event_name == 'pull_request_review'
        run: gh pr checkout "$PR_NUMBER"
        env:
          GH_TOKEN: {bt}
          PR_NUMBER: ${{{{ github.event.pull_request.number }}}}
{setup}
      - uses: max-sixty/tend@v1
        with:
          github_token: {bt}
          claude_code_oauth_token: {ct}
          bot_name: {bn}
          use_sticky_comment: ${{{{ github.event_name == 'pull_request_target' }}}}
          prompt: >-
            ${{{{ github.event_name == 'pull_request_target'
              && {prompt_expr}
              || format(
                'A review was submitted on your PR #{{0}} ({{1}}). Read the review and full PR context (description, diff, comments, CI status), then respond appropriately. If changes were requested, make them, commit, and push. If questions were asked, answer them.',
                github.event.pull_request.number,
                github.event.review.html_url
              ) }}}}
"""
    return GeneratedWorkflow(filename="tend-review.yaml", content=content)


# ---------------------------------------------------------------------------
# Mention
# ---------------------------------------------------------------------------

def generate_mention(cfg: Config) -> GeneratedWorkflow:
    bt = _bot_token(cfg)
    ct = _claude_token(cfg)
    bn = cfg.bot_name

    setup = _setup_yaml(cfg)
    perms = _permissions()
    pr = "(github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number)"

    content = f"""\
{HEADER}
name: tend-mention
on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  verify:
    if: |
      (github.event_name == 'issues' &&
        contains(github.event.issue.body, '@{bn}') &&
        github.event.issue.user.login != '{bn}') ||
      (github.event_name == 'issue_comment' &&
        github.event.comment.user.login != '{bn}') ||
      (github.event_name == 'pull_request_review_comment' &&
        github.event.comment.user.login != '{bn}')
    concurrency:
      group: ${{{{ github.workflow }}}}-${{{{ github.event.issue.number || github.event.pull_request.number }}}}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    outputs:
      should_run: ${{{{ steps.check.outputs.should_run }}}}
    steps:
      - name: Verify bot engagement
        id: check
        run: |
          # Mentions always run
          if [ "$EVENT_NAME" = "issues" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ -n "$COMMENT_BODY" ] && printf '%s\\n' "$COMMENT_BODY" | grep -qF '@{bn}'; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Non-mention: check bot engagement
          if [ "$EVENT_NAME" = "issue_comment" ]; then
            ISSUE_NUMBER="$ISSUE_OR_PR_NUMBER"

            if [ -z "$PR_URL" ]; then
              if [ "$ISSUE_AUTHOR" = "{bn}" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              if printf '%s\\n' "$ISSUE_BODY" | grep -qF '@{bn}'; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              BOT_COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \\
                --jq '[.[] | select(.user.login == "{bn}")] | length')
              if [ "$BOT_COMMENTS" -gt "0" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              echo "should_run=false" >> "$GITHUB_OUTPUT"; exit 0
            fi

            PR_NUMBER="$ISSUE_NUMBER"
          else
            PR_NUMBER="$EVENT_PR_NUMBER"
          fi

          PR_AUTHOR=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json author --jq '.author.login')
          if [ "$PR_AUTHOR" = "{bn}" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_REVIEWS=$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \\
            --jq '[.[] | select(.user.login == "{bn}")] | length')
          if [ "$BOT_REVIEWS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \\
            --jq '[.[] | select(.user.login == "{bn}")] | length')
          if [ "$BOT_COMMENTS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          echo "should_run=false" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: {bt}
          EVENT_NAME: ${{{{ github.event_name }}}}
          COMMENT_BODY: ${{{{ github.event.comment.body }}}}
          ISSUE_BODY: ${{{{ github.event.issue.body }}}}
          ISSUE_OR_PR_NUMBER: ${{{{ github.event.issue.number }}}}
          ISSUE_AUTHOR: ${{{{ github.event.issue.user.login }}}}
          PR_URL: ${{{{ github.event.issue.pull_request.url }}}}
          EVENT_PR_NUMBER: ${{{{ github.event.pull_request.number }}}}

      - name: React to mention
        if: |
          steps.check.outputs.should_run == 'true'
          && github.event.comment
          && contains(github.event.comment.body, '@{bn}')
        run: |
          gh api "repos/$REPO/issues/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || \\
          gh api "repos/$REPO/pulls/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || true
        env:
          REPO: ${{{{ github.repository }}}}
          COMMENT_ID: ${{{{ github.event.comment.id }}}}
          GH_TOKEN: {bt}

  handle:
    needs: verify
    if: needs.verify.outputs.should_run == 'true'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          token: {bt}

      - name: Check out PR branch
        if: |
          (github.event_name == 'issue_comment' && github.event.issue.pull_request.url != '') ||
          github.event_name == 'pull_request_review_comment'
        run: |
          PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq '.state')
          if [ "$PR_STATE" = "OPEN" ]; then
            gh pr checkout "$PR_NUMBER"
          else
            echo "::warning::PR is $PR_STATE — staying on default branch"
          fi
        env:
          GH_TOKEN: {bt}
          PR_NUMBER: ${{{{ github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number }}}}
{setup}
      - uses: max-sixty/tend@v1
        with:
          github_token: {bt}
          claude_code_oauth_token: {ct}
          bot_name: {bn}
          prompt: >-
            ${{{{ github.event_name == 'issues'
              && format('An issue was updated with a mention of you ({{0}}). Read it and respond.', github.event.issue.html_url)
              || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@{bn}')
                && format('You were mentioned in an inline review comment on PR #{{0}} ({{1}}, review comment ID {{2}}). Read the full PR context (description, diff, recent comments, CI status) and respond. If they are requesting changes, make the changes, commit, and push. Reply in the review thread using `gh api repos/{{3}}/pulls/{{0}}/comments/{{2}}/replies -f body="..."` — do not create a new top-level comment.', {pr}, github.event.comment.html_url, github.event.comment.id, github.repository))
              || (github.event_name == 'pull_request_review_comment'
                && format('A user left an inline review comment on a PR where you previously participated (PR #{{0}}, {{1}}, review comment ID {{2}}). Read the full context. Only respond if the comment is directed at you or requests changes. Reply in the review thread using `gh api repos/{{3}}/pulls/{{0}}/comments/{{2}}/replies -f body="..."`.', {pr}, github.event.comment.html_url, github.event.comment.id, github.repository))
              || (contains(github.event.comment.body, '@{bn}')
                && format('You were mentioned in a comment ({{0}}). Read the full issue or PR (description, diff, recent comments, CI status) and respond. If they are requesting changes, make the changes, commit, and push.', github.event.comment.html_url))
              || format('A user commented on an issue/PR where you previously participated ({{0}}). Read the full context. Only respond if the comment is directed at you, asks a question you can help with, or requests changes you can make. A comment that responds to concerns you raised in a review is directed at you — briefly acknowledge that the concerns are resolved (or explain why they are not). If the conversation is between humans, exit silently.', github.event.comment.html_url)
            }}}}
"""
    return GeneratedWorkflow(filename="tend-mention.yaml", content=content)


# ---------------------------------------------------------------------------
# Triage
# ---------------------------------------------------------------------------

def generate_triage(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("triage", WorkflowConfig())
    prompt = (wf.prompt or "/tend:tend-triage {issue_number}").replace(
        "{issue_number}", "${{ github.event.issue.number }}"
    )
    bt = _bot_token(cfg)
    ct = _claude_token(cfg)
    bn = cfg.bot_name
    db = cfg.default_branch

    setup = _setup_yaml(cfg)
    perms = _permissions()

    content = f"""\
{HEADER}
name: tend-triage
on:
  issues:
    types: [opened]

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.event.issue.number }}}}
  cancel-in-progress: true

jobs:
  triage:
    if: >-
      github.event.issue.user.type != 'Bot' &&
      github.event.issue.user.login != '{bn}'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {db}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
      - uses: max-sixty/tend@v1
        with:
          github_token: {bt}
          claude_code_oauth_token: {ct}
          bot_name: {bn}
          prompt: |
            {prompt}
"""
    return GeneratedWorkflow(filename="tend-triage.yaml", content=content)


# ---------------------------------------------------------------------------
# CI Fix
# ---------------------------------------------------------------------------

def generate_ci_fix(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("ci-fix", WorkflowConfig())
    watched = wf.watched_workflows if wf.watched_workflows is not None else ["ci"]
    prompt = (wf.prompt or "/tend:tend-ci-fix {run_id}").replace(
        "{run_id}", "${{ github.event.workflow_run.id }}"
    )
    bt = _bot_token(cfg)
    ct = _claude_token(cfg)
    bn = cfg.bot_name
    db = cfg.default_branch

    setup = _setup_yaml(cfg)
    perms = _permissions(issues=False)
    watched_yaml = ", ".join(f'"{w}"' for w in watched)

    content = f"""\
{HEADER}
name: tend-ci-fix
on:
  workflow_run:
    workflows: [{watched_yaml}]
    types: [completed]
    branches: [{db}]

jobs:
  fix-ci:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {db}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
      - uses: max-sixty/tend@v1
        with:
          github_token: {bt}
          claude_code_oauth_token: {ct}
          bot_name: {bn}
          prompt: |
            {prompt}
            - Run URL: ${{{{ github.event.workflow_run.html_url }}}}
            - Commit: ${{{{ github.event.workflow_run.head_sha }}}}
            - Commit message: ${{{{ github.event.workflow_run.head_commit.message }}}}
"""
    return GeneratedWorkflow(filename="tend-ci-fix.yaml", content=content)


# ---------------------------------------------------------------------------
# Scheduled (nightly, renovate)
# ---------------------------------------------------------------------------

def _generate_scheduled(cfg: Config, name: str, default_cron: str, default_prompt: str) -> GeneratedWorkflow:
    wf = cfg.workflows.get(name, WorkflowConfig())
    cron = wf.cron or default_cron
    prompt = wf.prompt or default_prompt
    bt = _bot_token(cfg)
    ct = _claude_token(cfg)
    bn = cfg.bot_name
    db = cfg.default_branch

    setup = _setup_yaml(cfg)
    perms = _permissions()

    prompt_lines = "\n".join(f"            {line}" for line in prompt.split("\n"))
    prompt_yaml = f"prompt: |\n{prompt_lines}"

    content = f"""\
{HEADER}
name: tend-{name}
on:
  schedule:
    - cron: "{cron}"
  workflow_dispatch:

jobs:
  {name}:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
{perms}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: {db}
          fetch-depth: 0
          fetch-tags: true
          token: {bt}
{setup}
      - uses: max-sixty/tend@v1
        with:
          github_token: {bt}
          claude_code_oauth_token: {ct}
          bot_name: {bn}
          {prompt_yaml}
"""
    return GeneratedWorkflow(filename=f"tend-{name}.yaml", content=content)


def generate_nightly(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(cfg, "nightly", "17 6 * * *", "/tend:tend-nightly")


def generate_renovate(cfg: Config) -> GeneratedWorkflow:
    return _generate_scheduled(cfg, "renovate", "17 9 * * 0", "/tend:tend-renovate")


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

GENERATORS: dict[str, Callable[[Config], GeneratedWorkflow]] = {
    "review": generate_review,
    "mention": generate_mention,
    "triage": generate_triage,
    "ci-fix": generate_ci_fix,
    "nightly": generate_nightly,
    "renovate": generate_renovate,
}


def generate_all(cfg: Config) -> list[GeneratedWorkflow]:
    """Generate all enabled workflows."""
    results = []
    for name, gen_fn in GENERATORS.items():
        wf_cfg = cfg.workflows.get(name, WorkflowConfig())
        if wf_cfg.enabled:
            results.append(gen_fn(cfg))
    return results
