"""Workflow definitions and YAML rendering."""

from __future__ import annotations

import copy
import io
import textwrap
from collections.abc import Callable
from dataclasses import dataclass
from importlib.metadata import version

import click
from jinja2 import Environment, StrictUndefined
from jinja2.runtime import Macro
from ruamel.yaml import YAML

from tend.config import Config, WorkflowConfig

# Variable delimiters are swapped from `{{`/`}}` to `<<`/`>>` so GitHub
# Actions expressions (`${{ github.foo }}`, ubiquitous in generated YAML)
# pass through templates unchanged. Block tags `{% if %} ... {% endif %}`
# stay default — GHA never uses that form. trim_blocks + lstrip_blocks let
# control-flow tags be indented without polluting output.
_JINJA = Environment(
    autoescape=False,
    trim_blocks=True,
    lstrip_blocks=True,
    undefined=StrictUndefined,
    keep_trailing_newline=True,
    variable_start_string="<<",
    variable_end_string=">>",
)

# ruamel.yaml defaults to YAML 1.2, where `on`/`yes`/`no`/`off` are strings,
# not booleans — sidesteps PyYAML's `on:` → True trap and the Norway problem.
# typ="rt" preserves insertion order and per-scalar style (matters for diff
# stability on regen); typ="safe" would sort keys alphabetically.
_YAML_BLOCK = YAML(typ="rt", pure=True)
_YAML_BLOCK.default_flow_style = False
_YAML_BLOCK.width = 200
_YAML_BLOCK.allow_unicode = True
# Round-trip explicit quoting on scalars (e.g. `cron: "17 6 * * *"` stays
# quoted). Without this, ruamel drops quotes on any string that's safe to
# unquote under YAML 1.2 — a meaningless style churn on regen.
_YAML_BLOCK.preserve_quotes = True
# Match the hand-rendered templates' 6-space `- uses:` under `steps:` (the
# `-` lives at parent-column + offset, the content at parent-column +
# sequence). Without this, `_apply_extras`-applied workflows reformat every
# step block (4→6 column for `-`, 4→8 for content) on regen — a churn diff
# for any consumer with `workflow_extra` or per-job overrides.
_YAML_BLOCK.indent(mapping=2, sequence=4, offset=2)

# Stamping the generator's own version into the header gives downstream
# nightly regen a stable anchor for detecting tend version bumps (see
# plugins/tend-ci-runner/skills/nightly/SKILL.md, Step 6) regardless of what
# templates pin for `uvx tend@...` or the action tag.
_TEND_VERSION = version("tend")
HEADER = f"""\
# Generated by tend {_TEND_VERSION}. Regenerate with: uvx tend@latest init
#
# Do not edit this file directly — it will be overwritten on regeneration.
# To customize behavior, edit the relevant skill (for example,
# `running-tend`) in this repo's .claude/skills/ directory, or open an issue at
# https://github.com/max-sixty/tend/issues for changes that need to
# happen upstream in the tend-ci-runner plugin.
"""

# Available to every template without being passed to render().
_JINJA.globals["header"] = HEADER
_JINJA.globals["tend_version"] = _TEND_VERSION


# The action ref pins to the generator's own release tag. Both actions ship
# from this repo (Codex variant lives under /codex/); release tags are
# immutable per docs/security-model.md, so the pin is a stable supply-chain
# anchor. Consumers move forward via the nightly `uvx tend@latest init` regen
# pulling a newer generator, which restamps a newer tag as a reviewable diff
# in their own repo. `version("tend")` only resolves to an existing tag when
# generation runs from a released package — generating from in-tree source
# pins a tag that does not exist yet; never commit those workflows (see
# CLAUDE.md).
#
# Claude emits both `claude_code_oauth_token` and `anthropic_api_key`
# unconditionally; the action validates exactly one is set and forwards both
# to claude-code-action, which treats empty as absent. Codex follows the same
# pattern (auth.json wins over api-key when both configured). Sticky comments
# are Claude-only — Codex posts via gh from inside skill prompts.
_MACROS = _JINJA.from_string("""\
{% macro agent_step(cfg, prompt_body, use_sticky_comment=False, if_condition='') %}
{% if cfg.harness == 'claude' %}
      - uses: max-sixty/tend@<<tend_version>>
{% else %}
      - uses: max-sixty/tend/codex@<<tend_version>>
{% endif %}
{% if if_condition %}
        if: <<if_condition>>
{% endif %}
        with:
          github_token: ${{ secrets.<<cfg.bot_token_secret>> }}
{% if cfg.harness == 'claude' %}
          claude_code_oauth_token: ${{ secrets.<<cfg.claude_token_secret>> }}
          anthropic_api_key: ${{ secrets.<<cfg.anthropic_api_key_secret>> }}
{% else %}
          openai_api_key: ${{ secrets.<<cfg.openai_key_secret>> }}
          codex_auth_json: ${{ secrets.<<cfg.codex_auth_json_secret>> }}
{% if cfg.effort %}
          effort: <<cfg.effort>>
{% endif %}
{% endif %}
          bot_name: <<cfg.bot_name>>
          model: <<cfg.model>>
{% if use_sticky_comment and cfg.harness == 'claude' %}
          use_sticky_comment: true
{% endif %}
          <<prompt_body>>
{%- endmacro %}

{# Permissions block at column 6. `issues` defaults to True because every
   workflow except ci-fix needs it. The trailing inline conditional avoids
   the trim_blocks-eats-the-separator issue between `actions: read` and
   `      issues: write` that arises with `{% if %}` on its own line. #}
{% macro permissions(issues=True) %}
      contents: write
      pull-requests: write
      id-token: write
      actions: read<<'\n      issues: write' if issues else ''>>
{%- endmacro %}

{# Skip a job when running outside the canonical owner. Compares
   `github.repository_owner` against the configured owner: `secrets` isn't
   available in `jobs.<job_id>.if`, and `github.event.repository.fork` is null
   for `schedule` events, so the owner string is the only check that works
   across all the affected event types.

   Two shapes:
   - fork_guard_if(cfg): emits `    if: <expr>` on its own line, or nothing
   - fork_guard_prefix(cfg): emits `<expr> && ` inline, or nothing — used
     when the job already has an `if:` (e.g. ci-fix's conclusion check) #}
{% macro fork_guard_if(cfg) %}
{% if cfg.repo_owner %}
    if: github.repository_owner == '<<cfg.repo_owner|replace("'", "''")>>'
{% endif %}
{%- endmacro %}

{% macro fork_guard_prefix(cfg) -%}
{% if cfg.repo_owner %}github.repository_owner == '<<cfg.repo_owner|replace("'", "''")>>' && {% endif %}
{%- endmacro %}

{# Shared `actions/checkout@v6` step. `ref` defaults to the configured default
   branch; pass `None` to omit (mention reuses the runner's default checkout
   ref), or any GHA expression for review's pr_ref dispatch. `if_condition`
   gates the step (used by notifications' skip_condition). #}
{% macro checkout(cfg, ref=None, if_condition='') %}
      - uses: actions/checkout@v6
{% if if_condition %}
        if: <<if_condition>>
{% endif %}
        with:
{% if ref %}
          ref: <<ref>>
{% endif %}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.<<cfg.bot_token_secret>> }}
{%- endmacro %}

{# YAML block scalar prompt at column 10, with the supplied text indented at
   column 12. Used by workflows whose prompt is just the bare invocation
   (triage, scheduled, notifications); review and ci-fix have richer prompt
   shapes that they inline. #}
{% macro block_prompt(prompt) -%}
prompt: |
<<prompt|indent(12, first=True, blank=True)>>
{%- endmacro %}
""")

# Make every macro defined in _MACROS available in workflow templates
# without requiring explicit `{% from 'macros.j2' import ... %}` imports.
_JINJA.globals.update(
    {name: val for name, val in vars(_MACROS.module).items() if isinstance(val, Macro)}
)


# Step keys are emitted in this order: step kind (uses/run) first, then
# metadata, then nested tables. Matches the hand-rendered template style;
# adopters' YAML order is otherwise preserved as-is.
_STEP_FIELD_ORDER = [
    "uses",
    "run",
    "name",
    "id",
    "if",
    "shell",
    "working-directory",
    "continue-on-error",
    "timeout-minutes",
    "with",
    "env",
]


def _setup_yaml(cfg: Config, condition: str = "") -> str:
    """Render setup steps as YAML at column 6.

    Returns empty string when no steps, or newline-prefixed block when present,
    so templates can write `<<setup>>` without extra blank lines.

    When *condition* is set, steps without an explicit `if:` receive one so
    they only run when the pre-check found work. Steps that already specify
    `if:` are left alone (with a warning) — their condition wins.
    """
    if not cfg.setup:
        return ""
    steps = []
    for step in cfg.setup:
        fields = dict(step.fields)
        if condition:
            if "if" in fields:
                click.echo(
                    "Warning: setup step has an explicit `if:`; the "
                    "notifications pre-check guard will not be added. "
                    "The step runs based on your condition alone.",
                    err=True,
                )
            else:
                fields["if"] = condition
        ordered = {k: fields[k] for k in _STEP_FIELD_ORDER if k in fields}
        for k, v in fields.items():
            ordered.setdefault(k, v)
        steps.append(ordered)
    buf = io.StringIO()
    _YAML_BLOCK.dump(steps, buf)
    return "\n" + textwrap.indent(buf.getvalue().rstrip(), "    ") + "\n"


@dataclass
class GeneratedWorkflow:
    filename: str
    content: str


# ---------------------------------------------------------------------------
# Review
# ---------------------------------------------------------------------------


def _escape_braces(prompt: str, placeholder: str) -> tuple[str, bool]:
    """Escape literal braces in a prompt, preserving only {placeholder}.

    Returns (escaped_prompt, needs_format). In the escaped prompt, {placeholder}
    is replaced with {0} for use with GitHub Actions format(), and all other
    braces are doubled to prevent format() from interpreting them.
    """
    sentinel = "\x00PLACEHOLDER\x00"
    text = prompt.replace(f"{{{placeholder}}}", sentinel)
    # Double all remaining braces so format() treats them as literals
    text = text.replace("{", "{{").replace("}", "}}")
    has_placeholder = sentinel in text
    text = text.replace(sentinel, "{0}")
    return text, has_placeholder


_REVIEW_TMPL = _JINJA.from_string("""\
{%- set prompt_body %}prompt: >-
            ${{ <<prompt_expr>> }}{%- endset -%}
<<header>>
name: tend-review
on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  review:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    permissions:
<<permissions()>>
    steps:
      # GitHub only materializes refs/pull/N/merge for mergeable PRs — on
      # conflicting PRs it 404s and every downstream step cascades as skipped.
      # Probe first and fall back to /head so review always runs; on fallback
      # the review sees the PR branch in isolation rather than the post-merge
      # tree.
      - name: Resolve PR checkout ref
        id: pr_ref
        env:
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          if gh api "repos/${{ github.repository }}/git/ref/pull/$PR/merge" --silent 2>/dev/null; then
            echo "ref=refs/pull/$PR/merge" >> "$GITHUB_OUTPUT"
          else
            echo "ref=refs/pull/$PR/head" >> "$GITHUB_OUTPUT"
            echo "::notice::refs/pull/$PR/merge unavailable (likely merge conflict); falling back to /head"
          fi
<<checkout(cfg, ref='${{ steps.pr_ref.outputs.ref }}')>>
<<setup>>
<<agent_step(cfg, prompt_body, use_sticky_comment=True)>>
""")


def generate_review(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("review", WorkflowConfig())
    raw_prompt = wf.prompt or cfg.default_prompt("review", "{pr_number}")
    format_body, needs_format = _escape_braces(raw_prompt, "pr_number")
    escaped = format_body.replace("'", "''")
    if needs_format:
        prompt_expr = f"format('{escaped}', github.event.pull_request.number)"
    else:
        prompt_expr = f"'{escaped}'"

    content = _REVIEW_TMPL.render(
        cfg=cfg,
        setup=_setup_yaml(cfg),
        prompt_expr=prompt_expr,
    )
    return GeneratedWorkflow(filename="tend-review.yaml", content=content)


# ---------------------------------------------------------------------------
# Mention
# ---------------------------------------------------------------------------


# Continuation lines inside a folded `>-` scalar are indented one level
# deeper than the `prompt:` key. The agent step renders fields at column 10;
# continuation goes at column 12.
_MENTION_TMPL = _JINJA.from_string("""\
{%- set pr = "(github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number)" -%}
{%- set prompt_body %}prompt: >-
            ${{ steps.delay.outputs.seconds
            && format('This job started {0}s after the triggering event (over ~40s means it was queued). ',
            steps.delay.outputs.seconds) || '' }}Before acting,
            check recent comments: exit silently if the bot already responded
            to the trigger; handle any other unaddressed comments too.

            ${{ github.event_name == 'issues'
              && format('An issue was updated with a mention of you ({0}). Read it and respond.', github.event.issue.html_url)
              || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@<<cfg.bot_name>>')
                && format('You were mentioned in an inline review comment on PR #{0} ({1}, comment ID {2}). Read the full context, then respond. If changes are requested, make them, commit, and push.', <<pr>>, github.event.comment.html_url, github.event.comment.id))
              || (github.event_name == 'pull_request_review_comment'
                && format('An inline review comment was posted on a PR where you previously participated (PR #{0}, {1}, comment ID {2}). Read the full context. Only respond if the comment is directed at you or requests changes.', <<pr>>, github.event.comment.html_url, github.event.comment.id))
              || (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@<<cfg.bot_name>>')
                && format('A review was submitted on PR #{0} that mentions you ({1}, review ID {2}). Read the review and full context, then respond. If changes were requested, make them, commit, and push.', github.event.pull_request.number, github.event.review.html_url, github.event.review.id))
              || (github.event_name == 'pull_request_review'
                && format('A review was submitted on a PR where you previously participated (PR #{0}, {1}, review ID {2}). Read the review and full context. If the review requests changes or asks questions, respond appropriately. If the review approves or is between humans, exit silently.', github.event.pull_request.number, github.event.review.html_url, github.event.review.id))
              || (contains(github.event.comment.body, '@<<cfg.bot_name>>')
                && format('You were mentioned in a comment ({0}). Read the full context and respond. If changes are requested, make them, commit, and push.', github.event.comment.html_url))
              || format('A user commented on an issue/PR where you previously participated ({0}). Read the full context. Only respond if the comment is directed at you, asks a question you can help with, or requests changes you can make. If the conversation is between other participants, exit silently.', github.event.comment.html_url)
            }}{%- endset -%}
<<header>>
name: tend-mention
on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]
  # Works for same-repo PRs only; secrets unavailable on fork PRs (no _target variant exists)
  pull_request_review:
    types: [submitted]
  # `created` is intentionally absent. Modern GitHub fires *both*
  # pull_request_review and pull_request_review_comment for every newly-created
  # inline comment (the standalone POST /pulls/PR/comments endpoint, the
  # /replies endpoint, the "Add single comment" UI button, and reviews
  # submitted with inline comments — all empirically verified). Subscribing to
  # `created` would produce a duplicate workflow run that collides on the
  # tend-mention-handle-PR concurrency group, with the loser cancelled and
  # posted as a CANCELLED check_run on the PR head SHA — which renders the
  # PR's statusCheckRollup as FAILURE even though the bot did its job from the
  # sibling run. Edits have no sibling event (review submissions don't fire on
  # edits), so we still need to listen for `edited` to catch edit-to-summon
  # ("@bot" added to an existing comment after the fact).
  pull_request_review_comment:
    types: [edited]

jobs:
  verify:
    # Filter out fork PRs for review events — secrets are unavailable there
    # (no _target variant exists). The notifications workflow polls for these.
    # Skip comments on `tend-outage` issues: the action's Report-failure step
    # auto-comments on those when Claude invocation fails, and without this
    # guard those comments re-trigger tend-mention during a persistent outage
    # (e.g. Anthropic 401), producing a self-sustaining ~1 run/minute loop
    # until the outage clears. The prompt's self-loop guard can't help here
    # because the model never executes — the action fails before Claude starts.
    if: |
      (github.event_name == 'issues' &&
        contains(github.event.issue.body, '@<<cfg.bot_name>>')) ||
      (github.event_name == 'issue_comment' &&
        !contains(github.event.issue.labels.*.name, 'tend-outage')) ||
      (github.event_name == 'pull_request_review_comment' &&
        github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_review' &&
        github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-24.04
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Verify bot engagement
        id: check
        run: |
          # Mentions always run
          if [ "$EVENT_NAME" = "issues" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ -n "$COMMENT_BODY" ] && printf '%s\\n' "$COMMENT_BODY" | grep -qF '@<<cfg.bot_name>>'; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # pull_request_review payloads include review.body (checked above)
          # but NOT the bodies of inline comments attached to the review.
          # Fetch them so a first-contact @-mention inside an inline comment
          # is detected on PRs where the bot has no prior engagement.
          if [ "$EVENT_NAME" = "pull_request_review" ] && [ -n "$REVIEW_ID" ]; then
            if gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$EVENT_PR_NUMBER/reviews/$REVIEW_ID/comments" \\
                 --jq '.[].body' | grep -qF '@<<cfg.bot_name>>'; then
              echo "should_run=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          # Non-mention: check bot engagement
          if [ "$EVENT_NAME" = "issue_comment" ]; then
            ISSUE_NUMBER="$ISSUE_OR_PR_NUMBER"

            if [ -z "$PR_URL" ]; then
              if [ "$ISSUE_AUTHOR" = "<<cfg.bot_name>>" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              if printf '%s\\n' "$ISSUE_BODY" | grep -qF '@<<cfg.bot_name>>'; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              BOT_COMMENTS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \\
                --jq '[.[] | select(.user.login == "<<cfg.bot_name>>")] | length')
              if [ "$BOT_COMMENTS" -gt "0" ]; then
                echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
              fi
              echo "should_run=false" >> "$GITHUB_OUTPUT"; exit 0
            fi

            PR_NUMBER="$ISSUE_NUMBER"
          else
            PR_NUMBER="$EVENT_PR_NUMBER"
          fi

          PR_AUTHOR=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json author --jq '.author.login')
          if [ "$PR_AUTHOR" = "<<cfg.bot_name>>" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_REVIEWS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \\
            --jq '[.[] | select(.user.login == "<<cfg.bot_name>>")] | length')
          if [ "$BOT_REVIEWS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          BOT_COMMENTS=$(gh api --paginate "repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \\
            --jq '[.[] | select(.user.login == "<<cfg.bot_name>>")] | length')
          if [ "$BOT_COMMENTS" -gt "0" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"; exit 0
          fi

          echo "should_run=false" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}
          EVENT_NAME: ${{ github.event_name }}
          COMMENT_BODY: ${{ github.event.comment.body || github.event.review.body }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_OR_PR_NUMBER: ${{ github.event.issue.number }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          PR_URL: ${{ github.event.issue.pull_request.url }}
          EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
          REVIEW_ID: ${{ github.event.review.id }}

      - name: React to mention
        if: |
          steps.check.outputs.should_run == 'true'
          && github.event.comment
          && contains(github.event.comment.body, '@<<cfg.bot_name>>')
        run: |
          gh api "repos/$REPO/issues/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || \\
          gh api "repos/$REPO/pulls/comments/$COMMENT_ID/reactions" -f content=eyes 2>/dev/null || true
        env:
          REPO: ${{ github.repository }}
          COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}

  handle:
    needs: verify
    if: needs.verify.outputs.should_run == 'true'
    concurrency:
      group: ${{ github.workflow }}-handle-${{ github.event.issue.number || github.event.pull_request.number }}
      cancel-in-progress: false
    runs-on: ubuntu-24.04
    permissions:
<<permissions()>>
    steps:
<<checkout(cfg)>>
<<setup>>
      - name: Check out PR branch
        if: |
          (github.event_name == 'issue_comment' && github.event.issue.pull_request.url != '') ||
          github.event_name == 'pull_request_review_comment' ||
          github.event_name == 'pull_request_review'
        run: |
          PR_STATE=$(gh pr view "$PR_NUMBER" --json state --jq '.state')
          if [ "$PR_STATE" = "OPEN" ]; then
            gh pr checkout "$PR_NUMBER"
          else
            echo "::warning::PR is $PR_STATE — staying on default branch"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}
          PR_NUMBER: ${{ github.event_name == 'issue_comment' && github.event.issue.number || github.event.pull_request.number }}

      - name: Compute queue delay
        id: delay
        run: |
          if [ -z "$EVENT_TS" ]; then
            echo "seconds=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          event_epoch=$(date -d "$EVENT_TS" +%s)
          echo "seconds=$(( $(date +%s) - event_epoch ))" >> "$GITHUB_OUTPUT"
        env:
          EVENT_TS: ${{ github.event.comment.created_at || github.event.review.submitted_at || github.event.issue.updated_at }}

<<agent_step(cfg, prompt_body)>>

      - name: Remove eyes reaction
        if: |
          always()
          && github.event.comment
          && contains(github.event.comment.body, '@<<cfg.bot_name>>')
        run: |
          for KIND in issues pulls; do
            REACTION_ID=$(gh api "repos/$REPO/$KIND/comments/$COMMENT_ID/reactions?content=eyes" \\
              --jq ".[] | select(.user.login == \\"$BOT_NAME\\") | .id" 2>/dev/null | head -n1)
            if [ -n "$REACTION_ID" ]; then
              gh api -X DELETE "repos/$REPO/$KIND/comments/$COMMENT_ID/reactions/$REACTION_ID" 2>/dev/null && break
            fi
          done
        env:
          REPO: ${{ github.repository }}
          COMMENT_ID: ${{ github.event.comment.id }}
          BOT_NAME: <<cfg.bot_name>>
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}
""")


def generate_mention(cfg: Config) -> GeneratedWorkflow:
    content = _MENTION_TMPL.render(cfg=cfg, setup=_setup_yaml(cfg))
    return GeneratedWorkflow(filename="tend-mention.yaml", content=content)


# ---------------------------------------------------------------------------
# Triage
# ---------------------------------------------------------------------------


_TRIAGE_TMPL = _JINJA.from_string("""\
<<header>>
name: tend-triage
on:
  issues:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  triage:
<<fork_guard_if(cfg)>>    runs-on: ubuntu-24.04
    permissions:
<<permissions()>>
    steps:
<<checkout(cfg, ref=cfg.default_branch)>>
<<setup>>
<<agent_step(cfg, block_prompt(prompt))>>
""")


def generate_triage(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("triage", WorkflowConfig())
    prompt = (wf.prompt or cfg.default_prompt("triage", "{issue_number}")).replace(
        "{issue_number}", "${{ github.event.issue.number }}"
    )

    content = _TRIAGE_TMPL.render(cfg=cfg, setup=_setup_yaml(cfg), prompt=prompt)
    return GeneratedWorkflow(filename="tend-triage.yaml", content=content)


# ---------------------------------------------------------------------------
# CI Fix
# ---------------------------------------------------------------------------


_CI_FIX_TMPL = _JINJA.from_string("""\
{%- set prompt_body %}prompt: |
            <<prompt>>
            - Run URL: ${{ github.event.workflow_run.html_url }}
            - Commit: ${{ github.event.workflow_run.head_sha }}
            - Commit message: ${{ github.event.workflow_run.head_commit.message }}{%- endset -%}
<<header>>
name: tend-ci-fix
on:
  workflow_run:
    workflows: <<watched|tojson>>
    types: [completed]
    branches: <<branches|tojson>>

jobs:
  fix-ci:
    if: <<fork_guard_prefix(cfg)>>github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-24.04
    permissions:
<<permissions(issues=False)>>
    steps:
<<checkout(cfg, ref=cfg.default_branch)>>
<<setup>>
<<agent_step(cfg, prompt_body)>>
""")


def generate_ci_fix(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("ci-fix", WorkflowConfig())
    if wf.watched_workflows is None:
        raise click.ClickException(
            "ci-fix requires watched_workflows — specify the CI workflow(s) to monitor.\n\n"
            "  workflows:\n"
            "    ci-fix:\n"
            '      watched_workflows: ["ci"]'
        )
    watched = wf.watched_workflows
    branches = wf.branches if wf.branches is not None else [cfg.default_branch]
    prompt = (wf.prompt or cfg.default_prompt("ci-fix", "{run_id}")).replace(
        "{run_id}", "${{ github.event.workflow_run.id }}"
    )

    content = _CI_FIX_TMPL.render(
        cfg=cfg,
        watched=watched,
        branches=branches,
        setup=_setup_yaml(cfg),
        prompt=prompt,
    )
    return GeneratedWorkflow(filename="tend-ci-fix.yaml", content=content)


# ---------------------------------------------------------------------------
# Scheduled (nightly, weekly)
# ---------------------------------------------------------------------------


_SCHEDULED_TMPL = _JINJA.from_string("""\
<<header>>
name: tend-<<name>>
on:
  schedule:
    - cron: "<<cron>>"
  workflow_dispatch:

jobs:
  <<name>>:
<<fork_guard_if(cfg)>>    runs-on: ubuntu-24.04
    permissions:
<<permissions()>>
    steps:
<<checkout(cfg, ref=cfg.default_branch)>>
<<setup>>
<<agent_step(cfg, block_prompt(prompt))>>
""")


# Default cron times target Anthropic's off-peak hours (outside weekday
# 8am–2pm ET / 12:00–18:00 UTC). Non-round minutes avoid thundering herd.
_SCHEDULED_DEFAULT_CRON = {
    "nightly": "17 6 * * *",
    "weekly": "17 9 * * 0",
    "review-runs": "47 7 * * *",
}


def _generate_scheduled(cfg: Config, name: str) -> GeneratedWorkflow:
    wf = cfg.workflows.get(name, WorkflowConfig())
    cron = wf.cron or _SCHEDULED_DEFAULT_CRON[name]
    prompt = wf.prompt or cfg.default_prompt(name)

    content = _SCHEDULED_TMPL.render(
        cfg=cfg,
        name=name,
        cron=cron,
        setup=_setup_yaml(cfg),
        prompt=prompt,
    )
    return GeneratedWorkflow(filename=f"tend-{name}.yaml", content=content)


_NOTIFICATIONS_TMPL = _JINJA.from_string("""\
<<header>>
name: tend-notifications
on:
  schedule:
    - cron: "<<cron>>"
  workflow_dispatch:

jobs:
  notifications:
<<fork_guard_if(cfg)>>    runs-on: ubuntu-24.04
    permissions:
<<permissions()>>
    steps:
      - name: Check for unread notifications
        id: check
        run: |
          COUNT=$(gh api notifications --jq 'length')
          if [ "$COUNT" = "0" ]; then
            echo "count=0" >> "$GITHUB_OUTPUT"
            echo "No unread notifications — skipping"
            exit 0
          fi

          # --- Layer B: drop notifications shadowed by recent dedicated runs ---
          # Event workflows mark their own notifications read via action.yaml's
          # post-step on success; this sweeps the case where Claude failed
          # (post-step is gated by `if: success()`) so the notification still
          # gets cleared without burning Claude turns to rediscover it.
          SINCE=$(date -u -d '30 minutes ago' +%Y-%m-%dT%H:%M:%SZ)
          RECENT_PRS=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs?created=>=$SINCE&per_page=50" --jq '[.workflow_runs[] | select(.name | test("^(tend-review|tend-mention|tend-triage|tend-ci-fix)$")) | .pull_requests[]?.number] | unique | .[]' || true)

          if [ -n "$RECENT_PRS" ]; then
            NOTIFS=$(gh api notifications)
            for pr in $RECENT_PRS; do
              echo "$NOTIFS" | jq -r --arg repo "$GITHUB_REPOSITORY" --arg pr "$pr" '.[] | select(.subject.url == "https://api.github.com/repos/" + $repo + "/pulls/" + $pr or .subject.url == "https://api.github.com/repos/" + $repo + "/issues/" + $pr) | .id' | while read -r tid; do
                [ -n "$tid" ] || continue
                gh api "notifications/threads/$tid" -X PATCH || true
              done
            done
          fi

          # --- Layer C: drop notifications on bot-authored closed PRs ---
          # The bot auto-subscribes to its own PRs. After merge/close, leftover
          # subscription notifications are pure noise — no action needed.
          NOTIFS=$(gh api notifications)
          echo "$NOTIFS" | jq -r --arg repo "$GITHUB_REPOSITORY" '.[] | select(.repository.full_name == $repo and .subject.type == "PullRequest") | .id' | while read -r tid; do
            [ -n "$tid" ] || continue
            PR_NUM=$(echo "$NOTIFS" | jq -r --arg tid "$tid" '.[] | select(.id == $tid) | .subject.url | split("/") | last')
            PR_INFO=$(gh api "repos/$GITHUB_REPOSITORY/pulls/$PR_NUM" --jq '"\\(.user.login) \\(.state)"' 2>/dev/null) || continue
            PR_AUTHOR=${PR_INFO%% *}
            PR_STATE=${PR_INFO##* }
            if [ "$PR_AUTHOR" = "<<cfg.bot_name>>" ] && [ "$PR_STATE" = "closed" ]; then
              gh api "notifications/threads/$tid" -X PATCH || true
            fi
          done

          # --- Layer D: count processable notifications ---
          # Same-repo notifications younger than 10 minutes are deferred: a
          # dedicated workflow (tend-review/mention/triage/ci-fix) is likely
          # still starting up or mid-flight and hasn't posted its response yet.
          # Processing them now risks duplicating work. Cross-repo notifications
          # are exempt — no dedicated workflow handles them.
          CUTOFF=$(date -u -d '10 minutes ago' +%Y-%m-%dT%H:%M:%SZ)
          REMAINING=$(gh api notifications)
          COUNT=$(echo "$REMAINING" | jq --arg repo "$GITHUB_REPOSITORY" --arg cutoff "$CUTOFF" '[.[] | select(.repository.full_name != $repo or .updated_at <= $cutoff)] | length')
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          if [ "$COUNT" = "0" ]; then
            TOTAL=$(echo "$REMAINING" | jq 'length')
            if [ "$TOTAL" = "0" ]; then
              echo "All notifications handled by pre-checks — skipping"
            else
              echo "$TOTAL notification(s) remain but all are fresh same-repo (deferred) — skipping"
            fi
          else
            echo "$COUNT processable notification(s) — proceeding"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.<<cfg.bot_token_secret>> }}

<<checkout(cfg, ref=cfg.default_branch, if_condition=skip_condition)>>
<<setup>><<agent_step(cfg, block_prompt(prompt), if_condition=skip_condition)>>
""")


def generate_notifications(cfg: Config) -> GeneratedWorkflow:
    wf = cfg.workflows.get("notifications", WorkflowConfig())
    cron = wf.cron or "*/15 * * * *"
    prompt = wf.prompt or cfg.default_prompt("notifications")

    skip_condition = (
        "steps.check.outputs.count != '0' || github.event_name == 'workflow_dispatch'"
    )

    content = _NOTIFICATIONS_TMPL.render(
        cfg=cfg,
        cron=cron,
        skip_condition=skip_condition,
        setup=_setup_yaml(cfg, condition=skip_condition),
        prompt=prompt,
    )
    return GeneratedWorkflow(filename="tend-notifications.yaml", content=content)


# ---------------------------------------------------------------------------
# Extras (workflow_extra / jobs pass-through)
# ---------------------------------------------------------------------------


def _deep_merge(base: dict, override: dict) -> dict:
    """RFC 7396 JSON Merge Patch: mappings deep-merge, scalars/lists replace.

    `base` is deep-copied so ruamel.yaml `CommentedMap` style metadata
    (key order, scalar quoting, sequence indentation) survives the merge —
    without this, `_apply_extras`-applied workflows lose all rendering
    style on every regen, even for keys the user didn't override.
    """
    result = copy.deepcopy(base)
    for key, value in override.items():
        if value is None:
            result.pop(key, None)
        elif isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _apply_extras(wf: GeneratedWorkflow, wf_cfg: WorkflowConfig) -> GeneratedWorkflow:
    """Merge workflow_extra and per-job extras into rendered YAML (RFC 7396)."""
    if not wf_cfg.workflow_extra and not wf_cfg.jobs:
        return wf

    data = _YAML_BLOCK.load(wf.content)

    if wf_cfg.workflow_extra:
        data = _deep_merge(data, wf_cfg.workflow_extra)

    if wf_cfg.jobs:
        jobs = data.get("jobs", {})
        for job_name, job_extra in wf_cfg.jobs.items():
            if job_name in jobs:
                jobs[job_name] = _deep_merge(jobs[job_name], job_extra)
            else:
                click.echo(
                    f"Warning: job '{job_name}' not found in {wf.filename} "
                    f"(known: {', '.join(sorted(jobs))})",
                    err=True,
                )

    # `typ="rt"` preserves the leading HEADER comment block on load, so it
    # round-trips into the dumped output. Don't prepend HEADER manually
    # here or it appears twice.
    buf = io.StringIO()
    _YAML_BLOCK.dump(data, buf)
    return GeneratedWorkflow(filename=wf.filename, content=buf.getvalue())


# ---------------------------------------------------------------------------
# Install test (one-shot, generated only with --with-install-test)
# ---------------------------------------------------------------------------


def generate_install_test(cfg: Config) -> GeneratedWorkflow:
    """One-shot pre-merge verification of an install PR.

    Generated only when `tend init --with-install-test` is passed. Lives on
    the install branch, fires on the install PR via `pull_request` (which
    uses the PR head's workflow file, not the default branch's), then
    disappears from the default branch on the first nightly regen — which
    runs `tend init` without the flag, and the init cleanup step removes
    any stale tend-*.yaml files.

    Verifies what can be checked without admin token or harness invocation:
    bot+harness secrets exist on the repo, and the committed workflow
    files match what the generator would produce now. Harness auth is
    exercised end-to-end by `tend-review` on the first post-merge PR.
    """
    bt_name = cfg.bot_token_secret
    if cfg.harness == "claude":
        harness_envs = (
            f"          CLAUDE_OAUTH: ${{{{ secrets.{cfg.claude_token_secret} }}}}\n"
            f"          ANTHROPIC_KEY: ${{{{ secrets.{cfg.anthropic_api_key_secret} }}}}"
        )
        harness_names = f"{cfg.claude_token_secret} or {cfg.anthropic_api_key_secret}"
        harness_check = '"$CLAUDE_OAUTH$ANTHROPIC_KEY"'
    else:
        harness_envs = (
            f"          CODEX_AUTH: ${{{{ secrets.{cfg.codex_auth_json_secret} }}}}\n"
            f"          OPENAI_KEY: ${{{{ secrets.{cfg.openai_key_secret} }}}}"
        )
        harness_names = f"{cfg.codex_auth_json_secret} or {cfg.openai_key_secret}"
        harness_check = '"$CODEX_AUTH$OPENAI_KEY"'

    content = f"""\
{HEADER}
name: tend-install-test
on:
  pull_request:
    paths:
      - .github/workflows/tend-*.yaml
      - .config/tend.yaml

jobs:
  install-test:
    # Same-repo PRs only. Fork PRs don't carry secrets and the workflow
    # is short-lived (removed on the next nightly regen), so cross-fork
    # validation isn't worth special-casing.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
      - name: Verify required secrets are set
        env:
          BOT_TOKEN: ${{{{ secrets.{bt_name} }}}}
{harness_envs}
        run: |
          missing=""
          [ -n "$BOT_TOKEN" ] || missing="$missing {bt_name}"
          if [ -z {harness_check} ]; then
            missing="$missing harness-auth(set {harness_names})"
          fi
          if [ -n "$missing" ]; then
            echo "::error::Missing repo secrets:$missing"
            exit 1
          fi
      - name: Verify generator output matches committed files
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          # `actions/checkout` doesn't set `origin/HEAD`, so the generator's
          # default-branch probe falls back to "main" and a repo with a
          # non-`main` default reports spurious drift. Query the remote.
          git remote set-head origin --auto
          # Pin the regen to the version in the committed header so a tend
          # release between local `init` and this CI run doesn't fail the
          # drift check for an irrelevant reason.
          HEADER=$(head -1 .github/workflows/tend-install-test.yaml)
          HEADER="${{HEADER#'# Generated by tend '}}"
          TEND_VERSION="${{HEADER%%'. Regenerate'*}}"
          uvx "tend@$TEND_VERSION" init --with-install-test
          if ! git diff --quiet .github/workflows/; then
            echo "::error::Committed workflows differ from 'uvx tend@$TEND_VERSION init --with-install-test' output. Run it locally and commit the result."
            git --no-pager diff .github/workflows/
            exit 1
          fi
"""
    return GeneratedWorkflow(filename="tend-install-test.yaml", content=content)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

GENERATORS: dict[str, Callable[[Config], GeneratedWorkflow]] = {
    "review": generate_review,
    "mention": generate_mention,
    "triage": generate_triage,
    "ci-fix": generate_ci_fix,
    "nightly": lambda cfg: _generate_scheduled(cfg, "nightly"),
    "weekly": lambda cfg: _generate_scheduled(cfg, "weekly"),
    "notifications": generate_notifications,
    "review-runs": lambda cfg: _generate_scheduled(cfg, "review-runs"),
}


def generate_all(
    cfg: Config, *, with_install_test: bool = False
) -> list[GeneratedWorkflow]:
    """Generate all enabled workflows.

    `with_install_test` opts in to the one-shot tend-install-test.yaml. The
    install-tend skill passes it during initial setup; the nightly regen
    runs without the flag so the install-test file is cleaned up once the
    install PR has landed.
    """
    results = []
    for name, gen_fn in GENERATORS.items():
        wf_cfg = cfg.workflows.get(name, WorkflowConfig())
        if not wf_cfg.enabled:
            continue
        if name == "ci-fix" and wf_cfg.watched_workflows is None:
            click.echo(
                "Skipping ci-fix: watched_workflows not configured. "
                "To enable, add to .config/tend.yaml:\n\n"
                "  workflows:\n"
                "    ci-fix:\n"
                '      watched_workflows: ["ci"]',
                err=True,
            )
            continue
        wf = gen_fn(cfg)
        wf = _apply_extras(wf, wf_cfg)
        results.append(wf)
    if with_install_test:
        wf = generate_install_test(cfg)
        wf_cfg = cfg.workflows.get("install-test", WorkflowConfig())
        wf = _apply_extras(wf, wf_cfg)
        results.append(wf)
    return results
